In [106]:
import time

import pandas as pd
import numpy as np
import os
from numpy.array_api import astype
from tqdm.notebook import tqdm

In [107]:
folder = "data/excel_files"

file_paths = [os.path.join(folder, f) for f in os.listdir(folder)]
file_paths

['data/excel_files/2024_9-10.xlsx',
 'data/excel_files/2024_11-12.xlsx',
 'data/excel_files/2024_5-6.xlsx',
 'data/excel_files/2025_5-6.xlsx',
 'data/excel_files/2025_3-4.xlsx',
 'data/excel_files/2024_3-4.xlsx',
 'data/excel_files/2024_1-2.xlsx',
 'data/excel_files/2025_1-2.xlsx',
 'data/excel_files/2024_7-8.xlsx',
 'data/excel_files/2025_7-8.xlsx']

In [108]:
df = pd.DataFrame()
for f in tqdm(file_paths):
    df = pd.concat([df, pd.read_excel(f, sheet_name="DATA", header=5)], ignore_index=True)

df = df[~df['EIC-код'].isin(['Grand Total', 'Загальний підсумок'])].copy()
df

  0%|          | 0/10 [00:00<?, ?it/s]

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год
0,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,1.0,19.264333,2.15221,5.697900
1,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,2.0,16.892233,2.15221,5.697900
2,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,3.0,15.382714,2.15221,5.697900
3,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,4.0,15.598360,2.15221,5.697900
4,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,5.0,14.735777,2.15221,5.697900
...,...,...,...,...,...,...,...,...,...,...
5454717,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,20.0,22.540932,1.76339,5.447321
5454718,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,21.0,24.207382,1.76339,5.447321
5454719,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,22.0,25.211150,1.76339,5.447321
5454720,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,23.0,22.579913,1.76339,5.447321
5454721,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,24.0,19.783005,1.76339,5.447321

In [109]:
static_data_dict = pd.read_excel("data/raw/8month2025.xlsx", sheet_name="Dict")
static_data_dict

,EIC-код,Унікод,АЗС,Тип,Область,Адреса,GPS-координати - Широта,GPS-координати - Довгота,ОСР код,ОСР опис
0,62Z3386096691495,40110200,АЗС_02,ОККО-міська,Львівська,"м. Львів, вул. Замарстинівська, 174",49.871014,24.020029,MGA-00900,Львів
1,62Z5700239654314,40110500,АЗС_05,ОККО-міська,Львівська,"м. Львів, вул. Клепарівська, 30 Б",49.853477,24.014784,MGA-00900,Львів
2,62Z8292498523912,40110700,АЗС_07,ОККО-міська,Львівська,"м. Львів, вул. Володимира Великого, 58",49.812439,23.984974,MGA-00900,Львів
3,62Z6337618908569,40111000,АЗС_10,ОККО-стандарт,Львівська,"м. Львів, вул. Липинського, 54 А",49.864338,24.039696,MGA-00900,Львів
4,62Z1180469265339,40111100,АЗС_11,ОККО-міська,Львівська,"Львів, вул. Джорджа Вашингтона, 12",49.813316,24.077612,MGA-00900,Львів
...,...,...,...,...,...,...,...,...,...,...
424,62Z2673921373211,41261600,АЗС_39,ОККО-трасова,Дніпропетровська,"с/р Новоолександрівська, вздовж АД М-04 Знам'я...",48.430910,34.944208,MGA-02400,Дніпро
425,62Z7841956124522,41062200,АЗС_36,ОККО-стандарт,Дніпропетровська,"м. Дніпро, вул. Каштанова, 4 К",48.501564,35.080823,MGA-02400,Дніпро
426,62Z5821574095639,41261800,АЗС_45,ОККО-міська,Дніпропетровська,"м. Дніпро, Полтавське шосе, 11 К",48.519610,34.989180,MGA-02400,Дніпро
427,62Z1528625762710,41261400,АЗС_46,ОККО-міська,Дніпропетровська,"м. Дніпро, вул. Робоча, 84",48.454806,35.003711,MGA-02400,Дніпро
428,62Z4670013981058,41261300,АЗС_40,ОККО-міська,Дніпропетровська,"м. Дніпро, вул. Панікахи, 31 г",48.399406,35.026860,MGA-02400,Дніпро

In [110]:
eic_code_to_missing_coords = {
    "62Z0602349894257": [48.763904006776954, 28.077456990197557],
    "62Z6035944504754": [49.153510259625534, 23.049801982501872],
    "62Z8888861892130": [48.309249416757545, 25.11895645420284],
    "62Z1209368438999": [49.78531388363913, 24.927028292321978],
    "62Z1771663109656": [49.453445499775405, 23.020911411362146],
    "62Z2532379651825": [49.29362429838761, 23.41030049170128],
    "62Z3261331410025": [49.56421176098104, 23.304357225434188],
    "62Z3627036877597": [48.51882104530565, 28.760435421364264],
    "62Z5422632680702": [50.22822399875523, 24.83726310970472],
    "62Z0763594350330": [49.369735771908296, 23.47527668624802],
    "62Z7029546479880": [49.77948499692157, 24.013408048459073],
    "62Z7072263538637": [49.86242688799433, 24.062926768794956],
    "62Z7766151236986": [50.46762760936502, 24.26123769025777],
    "62Z5064314448909": [48.149046045899055, 23.322957181272095],
    "62Z9342951787758": [49.28552561066835, 23.534192240667057],
    "62Z8521105012164": [48.36054435942602, 29.536275478873062],
    "62Z1142387881356": [49.76402754584019, 31.39902598856454],
    "62Z6624735969589": [48.94419405940688, 24.149295411716132],
    "62Z5956494916290": [49.95178196130912, 25.31699531547816],
    "62Z0717322121288": [48.207039717684104, 23.522199099176],
    "62Z568600499251K": [49.74638889010666, 31.486251700927244],
}

lat_map = {k: v[0] for k, v in eic_code_to_missing_coords.items()}
lon_map = {k: v[1] for k, v in eic_code_to_missing_coords.items()}

static_data_dict["GPS-координати - Широта"] = (
  static_data_dict["GPS-координати - Широта"]
  .replace(0, pd.NA)
  .fillna(static_data_dict["EIC-код"].map(lat_map))
)

static_data_dict["GPS-координати - Довгота"] = (
  static_data_dict["GPS-координати - Довгота"]
  .replace(0, pd.NA)
  .fillna(static_data_dict["EIC-код"].map(lon_map))
)
static_data_dict

/var/folders/5w/bchvy66s6vbgncfkws1skvf40000gp/T/ipykernel_82104/79516357.py:31: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .fillna(static_data_dict["EIC-код"].map(lat_map))
/var/folders/5w/bchvy66s6vbgncfkws1skvf40000gp/T/ipykernel_82104/79516357.py:37: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .fillna(static_data_dict["EIC-код"].map(lon_map))

,EIC-код,Унікод,АЗС,Тип,Область,Адреса,GPS-координати - Широта,GPS-координати - Довгота,ОСР код,ОСР опис
0,62Z3386096691495,40110200,АЗС_02,ОККО-міська,Львівська,"м. Львів, вул. Замарстинівська, 174",49.871014,24.020029,MGA-00900,Львів
1,62Z5700239654314,40110500,АЗС_05,ОККО-міська,Львівська,"м. Львів, вул. Клепарівська, 30 Б",49.853477,24.014784,MGA-00900,Львів
2,62Z8292498523912,40110700,АЗС_07,ОККО-міська,Львівська,"м. Львів, вул. Володимира Великого, 58",49.812439,23.984974,MGA-00900,Львів
3,62Z6337618908569,40111000,АЗС_10,ОККО-стандарт,Львівська,"м. Львів, вул. Липинського, 54 А",49.864338,24.039696,MGA-00900,Львів
4,62Z1180469265339,40111100,АЗС_11,ОККО-міська,Львівська,"Львів, вул. Джорджа Вашингтона, 12",49.813316,24.077612,MGA-00900,Львів
...,...,...,...,...,...,...,...,...,...,...
424,62Z2673921373211,41261600,АЗС_39,ОККО-трасова,Дніпропетровська,"с/р Новоолександрівська, вздовж АД М-04 Знам'я...",48.430910,34.944208,MGA-02400,Дніпро
425,62Z7841956124522,41062200,АЗС_36,ОККО-стандарт,Дніпропетровська,"м. Дніпро, вул. Каштанова, 4 К",48.501564,35.080823,MGA-02400,Дніпро
426,62Z5821574095639,41261800,АЗС_45,ОККО-міська,Дніпропетровська,"м. Дніпро, Полтавське шосе, 11 К",48.519610,34.989180,MGA-02400,Дніпро
427,62Z1528625762710,41261400,АЗС_46,ОККО-міська,Дніпропетровська,"м. Дніпро, вул. Робоча, 84",48.454806,35.003711,MGA-02400,Дніпро
428,62Z4670013981058,41261300,АЗС_40,ОККО-міська,Дніпропетровська,"м. Дніпро, вул. Панікахи, 31 г",48.399406,35.026860,MGA-02400,Дніпро

In [111]:
df = df.merge(static_data_dict, on='EIC-код', how='left', suffixes=('', '_dict'))
df

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,Унікод,АЗС,Тип,Область,Адреса,GPS-координати - Широта,GPS-координати - Довгота,ОСР код,ОСР опис
0,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,1.0,19.264333,2.15221,5.697900,40312900,АЗС_29,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород
1,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,2.0,16.892233,2.15221,5.697900,40312900,АЗС_29,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород
2,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,3.0,15.382714,2.15221,5.697900,40312900,АЗС_29,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород
3,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,4.0,15.598360,2.15221,5.697900,40312900,АЗС_29,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород
4,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,5.0,14.735777,2.15221,5.697900,40312900,АЗС_29,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5454708,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,20.0,22.540932,1.76339,5.447321,40116500,АЗС_65,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів
5454709,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,21.0,24.207382,1.76339,5.447321,40116500,АЗС_65,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів
5454710,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,22.0,25.211150,1.76339,5.447321,40116500,АЗС_65,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів
5454711,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,23.0,22.579913,1.76339,5.447321,40116500,АЗС_65,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів
5454712,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,24.0,19.783005,1.76339,5.447321,40116500,АЗС_65,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів

In [112]:
solar_dict = pd.read_excel("data/additional_data/ВхідніДані.xlsx", sheet_name="СЕС", header=0)
solar_dict = solar_dict[solar_dict['Plant Name'] != 'Total'].copy()
cols_to_rename = {
    'Unicod': 'Унікод',
    'Grid Connection Date': 'solar_install_date',
    'Max Power, kWt': 'max_solar',
}
solar_dict = solar_dict.rename(columns=cols_to_rename).copy()
solar_dict['Унікод'] = solar_dict['Унікод'].astype(int)
solar_dict = solar_dict[['Унікод', 'solar_install_date', 'max_solar']].copy()
solar_dict

       Унікод   solar_install_date  max_solar
0    60961300  2017-11-15 00:00:00       50.0
1    60960200  2018-06-16 00:00:00       30.0
2    40512900  2020-11-22 00:00:00       20.0
3    40561300  2020-11-26 00:00:00       15.0
4    40311500  2020-11-29 00:00:00       15.0
..        ...                  ...        ...
262  40117400  2025-06-23 00:00:00       12.0
263  40564400  2025-06-30 00:00:00       15.0
264  40513800  2025-06-28 00:00:00       15.0
265  40515200  2025-07-02 00:00:00       11.0
266  40266700  2025-06-19 00:00:00       16.0

[267 rows x 3 columns]

In [113]:
max_power_dict = pd.read_excel("data/additional_data/ВхідніДані.xlsx", sheet_name="Потужність", header=2)
cols_to_rename = {
    'Унікод АЗС': 'Унікод',
    'Існуюча потужність, кВт': 'max_power'
}
max_power_dict = max_power_dict.rename(columns=cols_to_rename).copy()
max_power_dict = max_power_dict[['Унікод', 'max_power']].copy()
max_power_dict

       Унікод  max_power
0    40110200       40.0
1    40110300      150.0
2    40110500       30.0
3    40110700       40.0
4    40110800       30.0
..        ...        ...
404  46061700      122.0
405  46062000       10.0
406  46062100       15.0
407  46062300       47.0
408  46062400       55.0

[409 rows x 2 columns]

In [114]:
df = df.merge(solar_dict, on='Унікод', how='left', suffixes=('', '_dict'))
df = df.merge(max_power_dict, on='Унікод', how='left', suffixes=('', '_dict'))
df

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,...,Тип,Область,Адреса,GPS-координати - Широта,GPS-координати - Довгота,ОСР код,ОСР опис,solar_install_date,max_solar,max_power
0,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,1.0,19.264333,2.15221,5.697900,...,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0
1,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,2.0,16.892233,2.15221,5.697900,...,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0
2,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,3.0,15.382714,2.15221,5.697900,...,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0
3,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,4.0,15.598360,2.15221,5.697900,...,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0
4,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,5.0,14.735777,2.15221,5.697900,...,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5454708,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,20.0,22.540932,1.76339,5.447321,...,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0
5454709,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,21.0,24.207382,1.76339,5.447321,...,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0
5454710,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,22.0,25.211150,1.76339,5.447321,...,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0
5454711,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,23.0,22.579913,1.76339,5.447321,...,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0
5454712,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,24.0,19.783005,1.76339,5.447321,...,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0

In [115]:
mask = (df['Дата'] <= df['solar_install_date']) | (df['solar_install_date'].isna())
df.loc[mask, 'max_solar'] = 0
df

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,...,Тип,Область,Адреса,GPS-координати - Широта,GPS-координати - Довгота,ОСР код,ОСР опис,solar_install_date,max_solar,max_power
0,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,1.0,19.264333,2.15221,5.697900,...,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0
1,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,2.0,16.892233,2.15221,5.697900,...,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0
2,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,3.0,15.382714,2.15221,5.697900,...,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0
3,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,4.0,15.598360,2.15221,5.697900,...,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0
4,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,5.0,14.735777,2.15221,5.697900,...,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5454708,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,20.0,22.540932,1.76339,5.447321,...,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0
5454709,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,21.0,24.207382,1.76339,5.447321,...,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0
5454710,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,22.0,25.211150,1.76339,5.447321,...,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0
5454711,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,23.0,22.579913,1.76339,5.447321,...,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0
5454712,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,24.0,19.783005,1.76339,5.447321,...,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0

In [116]:
df['max_power_present'] = np.where(df['max_power'].notna(), 'Yes', 'No')

mask = df['max_power'].isna()
df.loc[mask, 'max_power'] = (
    df.groupby('EIC-код')['Sum of кВт'].transform('max')
)

In [117]:
mask = (
    (df['Sum of кВт'] > 1.25 * df['max_power']) &
    ((df['Sum of кВт'] - df['max_power']) > 20)
)

df.loc[mask, ['EIC-код', 'Sum of кВт', 'max_power', 'max_power_present', 'Дата']]

                  EIC-код  Sum of кВт  max_power max_power_present       Дата
196186   62Z3584090129468   87.497367       60.0               Yes 2024-09-01
196187   62Z3584090129468   80.669079       60.0               Yes 2024-09-01
196188   62Z3584090129468   89.244138       60.0               Yes 2024-09-01
196189   62Z3584090129468   85.274203       60.0               Yes 2024-09-01
196190   62Z3584090129468   92.896479       60.0               Yes 2024-09-01
...                   ...         ...        ...               ...        ...
5150408  62Z4534322132001  170.502000       63.0               Yes 2025-08-31
5150409  62Z4534322132001  165.502000       63.0               Yes 2025-08-31
5150410  62Z4534322132001   88.501000       63.0               Yes 2025-08-31
5150412  62Z4534322132001  122.502000       63.0               Yes 2025-08-31
5150413  62Z4534322132001  191.002000       63.0               Yes 2025-08-31

[5828 rows x 5 columns]

In [118]:
df.loc[mask, ['EIC-код', 'Sum of кВт', 'max_power', 'max_power_present', 'Дата']]['EIC-код'].unique()

array(['62Z3584090129468', '62Z0101426517156', '62Z2483925041819',
       '62Z4534322132001', '62Z4869256917783', '62Z2655661084314',
       '62Z4948939192262', '62Z5644272506149', '62Z9512175266041',
       '62Z2986251549800', '62Z5611760007206', '62Z7156461265052',
       '62Z7878159195687'], dtype=object)

In [119]:
df[df['EIC-код'] == '62Z3584090129468'].loc[mask, ['EIC-код', 'Sum of кВт', 'max_power', 'max_power_present', 'Дата']]

                 EIC-код  Sum of кВт  max_power max_power_present       Дата
196186  62Z3584090129468   87.497367       60.0               Yes 2024-09-01
196187  62Z3584090129468   80.669079       60.0               Yes 2024-09-01
196188  62Z3584090129468   89.244138       60.0               Yes 2024-09-01
196189  62Z3584090129468   85.274203       60.0               Yes 2024-09-01
196190  62Z3584090129468   92.896479       60.0               Yes 2024-09-01
...                  ...         ...        ...               ...        ...
196890  62Z3584090129468  101.471538       60.0               Yes 2024-09-30
196891  62Z3584090129468  106.394258       60.0               Yes 2024-09-30
196892  62Z3584090129468  104.329891       60.0               Yes 2024-09-30
196893  62Z3584090129468   95.278440       60.0               Yes 2024-09-30
196894  62Z3584090129468   85.591798       60.0               Yes 2024-09-30

[464 rows x 5 columns]

In [120]:
df['Дата'] = pd.to_datetime(df['Дата'], errors='coerce')
df['Дата'] = df['Дата'] + pd.to_timedelta(df['Hour'].fillna(0), unit='h')
df

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,...,Область,Адреса,GPS-координати - Широта,GPS-координати - Довгота,ОСР код,ОСР опис,solar_install_date,max_solar,max_power,max_power_present
0,62Z0008583037334,Б,2024-09-01 01:00:00,2024.0,9.0,1.0,1.0,19.264333,2.15221,5.697900,...,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0,Yes
1,62Z0008583037334,Б,2024-09-01 02:00:00,2024.0,9.0,1.0,2.0,16.892233,2.15221,5.697900,...,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0,Yes
2,62Z0008583037334,Б,2024-09-01 03:00:00,2024.0,9.0,1.0,3.0,15.382714,2.15221,5.697900,...,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0,Yes
3,62Z0008583037334,Б,2024-09-01 04:00:00,2024.0,9.0,1.0,4.0,15.598360,2.15221,5.697900,...,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0,Yes
4,62Z0008583037334,Б,2024-09-01 05:00:00,2024.0,9.0,1.0,5.0,14.735777,2.15221,5.697900,...,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5454708,62Z9997819406173,Б,2025-08-31 20:00:00,2025.0,8.0,31.0,20.0,22.540932,1.76339,5.447321,...,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0,Yes
5454709,62Z9997819406173,Б,2025-08-31 21:00:00,2025.0,8.0,31.0,21.0,24.207382,1.76339,5.447321,...,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0,Yes
5454710,62Z9997819406173,Б,2025-08-31 22:00:00,2025.0,8.0,31.0,22.0,25.211150,1.76339,5.447321,...,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0,Yes
5454711,62Z9997819406173,Б,2025-08-31 23:00:00,2025.0,8.0,31.0,23.0,22.579913,1.76339,5.447321,...,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0,Yes
5454712,62Z9997819406173,Б,2025-09-01 00:00:00,2025.0,8.0,31.0,24.0,19.783005,1.76339,5.447321,...,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0,Yes

In [121]:
# --- 62Z3584090129468: drop data before 2024-10-01 ---
mask = (df['EIC-код'] == '62Z3584090129468') & (df['Дата'] < '2024-10-02')
df = df[~mask]

# --- 62Z0101426517156: cap 'Sum of кВт' at 210 ---
mask = df['EIC-код'] == '62Z0101426517156'
df.loc[mask & (df['Sum of кВт'] > 210), 'Sum of кВт'] = 210

mask = (df['EIC-код'] == '62Z0101426517156') & (df['Дата'] < '2025-01-01')
df = df[~mask]

# --- 62Z4869256917783: drop before 2025, scale 2025-05-07 09:00–2025-05-31 23:00 ---
mask_eic = df['EIC-код'] == '62Z4869256917783'
# Drop before 2025
df = df[~(mask_eic & (df['Дата'] < '2025-01-01'))]
# Recalculate mask after drop
mask_eic = df['EIC-код'] == '62Z4869256917783'
# Target window
mask_target = mask_eic & (df['Дата'] >= '2025-05-01 00:00:00') & (df['Дата'] <= '2025-06-01 00:00:00')
# Reference: April 2025 + June 2025
mask_ref = mask_eic & (
    ((df['Дата'] >= '2025-04-01') & (df['Дата'] < '2025-05-01')) |
    ((df['Дата'] >= '2025-06-01') & (df['Дата'] < '2025-07-01'))
)
ref_mean = df.loc[mask_ref, 'Sum of кВт'].mean()
target_mean = df.loc[mask_target, 'Sum of кВт'].mean()
if target_mean != 0:
    df.loc[mask_target, 'Sum of кВт'] *= ref_mean / target_mean

# --- 62Z2655661084314: scale 2025-04-01 09:00–2025-04-30 22:00 to mean of Mar+May 2025 ---
mask_eic = df['EIC-код'] == '62Z2655661084314'
mask_target = mask_eic & (df['Дата'] >= '2025-04-01') & (df['Дата'] < '2025-05-01')
mask_ref = mask_eic & (
    ((df['Дата'] >= '2025-03-01') & (df['Дата'] < '2025-04-01')) |
    ((df['Дата'] >= '2025-05-01') & (df['Дата'] < '2025-06-01'))
)
ref_mean = df.loc[mask_ref, 'Sum of кВт'].mean()
target_mean = df.loc[mask_target, 'Sum of кВт'].mean()
if target_mean != 0:
    df.loc[mask_target, 'Sum of кВт'] *= ref_mean / target_mean

# --- 62Z4948939192262: drop before 2024-05-05 ---
mask = (df['EIC-код'] == '62Z4948939192262') & (df['Дата'] < '2025-05-05')
df = df[~mask]

# --- 62Z5644272506149: drop before 2025-05-05 ---
mask = (df['EIC-код'] == '62Z5644272506149') & (df['Дата'] < '2025-05-05')
df = df[~mask]

# --- 62Z9512175266041: drop before 2025-05-05 ---
mask = (df['EIC-код'] == '62Z9512175266041') & (df['Дата'] < '2025-05-05')
df = df[~mask]

# --- 62Z2986251549800: drop before 2024-05-05 ---
mask = (df['EIC-код'] == '62Z2986251549800') & (df['Дата'] < '2024-05-05')
df = df[~mask]

# --- 62Z7878159195687: drop before 2024-11-01 ---
mask = (df['EIC-код'] == '62Z7878159195687') & (df['Дата'] < '2024-11-01')
df = df[~mask]

In [122]:
electricity_prices_df = pd.read_excel('data/raw/8month2025.xlsx', sheet_name="ЦіниРДН", header=2)[['Year', 'Month', 'Day', 'Година', 'Average of Ціна, грн без ПДВ/кВт']]

electricity_prices_df = electricity_prices_df[electricity_prices_df['Year'] != 'Grand Total'].copy()

electricity_prices_df['Дата'] = pd.to_datetime(
    electricity_prices_df[['Year', 'Month', 'Day']].assign(hour=electricity_prices_df['Година'])
)
electricity_prices_df

,Year,Month,Day,Година,"Average of Ціна, грн без ПДВ/кВт",Дата
0,2024,1.0,1.0,1.0,0.05700,2024-01-01 01:00:00
1,2024,1.0,1.0,2.0,0.05700,2024-01-01 02:00:00
2,2024,1.0,1.0,3.0,0.05555,2024-01-01 03:00:00
3,2024,1.0,1.0,4.0,0.03800,2024-01-01 04:00:00
4,2024,1.0,1.0,5.0,0.03200,2024-01-01 05:00:00
...,...,...,...,...,...,...
15594,2025,10.0,11.0,20.0,14.95073,2025-10-11 20:00:00
15595,2025,10.0,11.0,21.0,14.95057,2025-10-11 21:00:00
15596,2025,10.0,11.0,22.0,14.94907,2025-10-11 22:00:00
15597,2025,10.0,11.0,23.0,14.94767,2025-10-11 23:00:00
15598,2025,10.0,11.0,24.0,6.89051,2025-10-12 00:00:00

In [123]:
df = df.merge(
    electricity_prices_df[['Дата', 'Average of Ціна, грн без ПДВ/кВт']],
    on='Дата',
    how='left'
)

# replace values
df['Average of Ціна ЕЕ грн. без ПДВ/кВт*год'] = df['Average of Ціна, грн без ПДВ/кВт']

# optionally drop helper column
df = df.drop(columns=['Average of Ціна, грн без ПДВ/кВт'])

In [124]:
distr_prices_df = pd.read_excel('data/raw/8month2025.xlsx', sheet_name="Dist_price")
distr_prices_df

    Year  Month  Distr_price
0   2024      1        0.529
1   2024      2        0.529
2   2024      3        0.529
3   2024      4        0.529
4   2024      5        0.529
5   2024      6        0.529
6   2024      7        0.529
7   2024      8        0.529
8   2024      9        0.529
9   2024     10        0.529
10  2024     11        0.529
11  2024     12        0.529
12  2025      1        0.686
13  2025      2        0.686
14  2025      3        0.686
15  2025      4        0.686
16  2025      5        0.686
17  2025      6        0.686
18  2025      7        0.686
19  2025      8        0.686
20  2025      9        0.686
21  2025     10        0.686
22  2025     11        0.686
23  2025     12        0.686

In [125]:
# df = df.merge(
#     distr_prices_df[['Year', 'Month', 'Distr_price']],
#     on=['Year', 'Month'],
#     how='left'
# )
#
# # replace values
# df['Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год'] = df['Distr_price']
#
# # optionally drop helper column
# df = df.drop(columns=['Distr_price'])

In [126]:
df

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,...,Область,Адреса,GPS-координати - Широта,GPS-координати - Довгота,ОСР код,ОСР опис,solar_install_date,max_solar,max_power,max_power_present
0,62Z0008583037334,Б,2024-09-01 01:00:00,2024.0,9.0,1.0,1.0,19.264333,2.15221,5.60000,...,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0,Yes
1,62Z0008583037334,Б,2024-09-01 02:00:00,2024.0,9.0,1.0,2.0,16.892233,2.15221,3.98000,...,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0,Yes
2,62Z0008583037334,Б,2024-09-01 03:00:00,2024.0,9.0,1.0,3.0,15.382714,2.15221,3.00000,...,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0,Yes
3,62Z0008583037334,Б,2024-09-01 04:00:00,2024.0,9.0,1.0,4.0,15.598360,2.15221,1.45000,...,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0,Yes
4,62Z0008583037334,Б,2024-09-01 05:00:00,2024.0,9.0,1.0,5.0,14.735777,2.15221,1.00000,...,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород,2020-12-09 00:00:00,25.52,110.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5420395,62Z9997819406173,Б,2025-08-31 20:00:00,2025.0,8.0,31.0,20.0,22.540932,1.76339,14.89963,...,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0,Yes
5420396,62Z9997819406173,Б,2025-08-31 21:00:00,2025.0,8.0,31.0,21.0,24.207382,1.76339,14.90208,...,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0,Yes
5420397,62Z9997819406173,Б,2025-08-31 22:00:00,2025.0,8.0,31.0,22.0,25.211150,1.76339,14.90102,...,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0,Yes
5420398,62Z9997819406173,Б,2025-08-31 23:00:00,2025.0,8.0,31.0,23.0,22.579913,1.76339,14.89812,...,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0,Yes
5420399,62Z9997819406173,Б,2025-09-01 00:00:00,2025.0,8.0,31.0,24.0,19.783005,1.76339,6.69000,...,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів,2021-07-16 00:00:00,15.00,80.0,Yes

In [127]:
cols_to_leave = ['EIC-код',
                 # 'Група',
                 'Дата', 'Sum of кВт',
                 'Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год', 'Average of Ціна ЕЕ грн. без ПДВ/кВт*год', 'Тип',
                 'Область', 'GPS-координати - Широта', 'GPS-координати - Довгота', 'ОСР опис', 'Адреса', 'max_power', 'max_solar']

rename_cols = {
    'Дата': 'datetime',
    'Sum of кВт': 'sum_of_kWh',
    'EIC-код': 'eic_code',
    # 'Група': 'Група_cat',
    'Тип': 'station_type',
    'Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год': 'dist_price',
    'Average of Ціна ЕЕ грн. без ПДВ/кВт*год': 'elect_price',
    'Область': 'oblast',
    'GPS-координати - Широта': 'latitude',
    'GPS-координати - Довгота': 'longitude',
    'ОСР опис': 'osr_desc',
    'Адреса': 'address'
}

weather_cols_to_create = ['temperature_2m',
       'apparent_temperature', 'dew_point_2m', 'relative_humidity_2m',
       'precipitation', 'rain', 'snowfall', 'cloud_cover', 'cloud_cover_low',
       'cloud_cover_mid', 'cloud_cover_high', 'surface_pressure',
       'wind_speed_10m', 'wind_direction_10m', 'wind_gusts_10m',
       'shortwave_radiation', 'diffuse_radiation', 'direct_normal_irradiance', 'daylight_duration']

In [128]:
df = df[cols_to_leave].copy()
df = df.rename(columns=rename_cols)
df

,eic_code,datetime,sum_of_kWh,dist_price,elect_price,station_type,oblast,latitude,longitude,osr_desc,address,max_power,max_solar
0,62Z0008583037334,2024-09-01 01:00:00,19.264333,2.15221,5.60000,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,25.52
1,62Z0008583037334,2024-09-01 02:00:00,16.892233,2.15221,3.98000,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,25.52
2,62Z0008583037334,2024-09-01 03:00:00,15.382714,2.15221,3.00000,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,25.52
3,62Z0008583037334,2024-09-01 04:00:00,15.598360,2.15221,1.45000,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,25.52
4,62Z0008583037334,2024-09-01 05:00:00,14.735777,2.15221,1.00000,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,25.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5420395,62Z9997819406173,2025-08-31 20:00:00,22.540932,1.76339,14.89963,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,15.00
5420396,62Z9997819406173,2025-08-31 21:00:00,24.207382,1.76339,14.90208,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,15.00
5420397,62Z9997819406173,2025-08-31 22:00:00,25.211150,1.76339,14.90102,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,15.00
5420398,62Z9997819406173,2025-08-31 23:00:00,22.579913,1.76339,14.89812,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,15.00
5420399,62Z9997819406173,2025-09-01 00:00:00,19.783005,1.76339,6.69000,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,15.00

In [129]:
mask = (
    (df["eic_code"] == "62Z8521105012164") &
    (df["datetime"] <= "2024-06-01 00:00:00")
)

df = df.loc[~mask]

In [130]:
mask = df["eic_code"] == "62Z8937841078757"

df.loc[mask, "dist_price"] = 2.31163

In [131]:
print(f"Stations before dropping: {len(df['eic_code'].unique())}, rows: {len(df)}")

global_end = df["datetime"].max()

# station-level stats
g = df.groupby("eic_code")["datetime"]

station_stats = pd.DataFrame({
    "start": g.min(),
    "end": g.max(),
    "n_hours": g.count()
})

# rule 1: must have data near dataset end (within 7 days tolerance)
station_stats["reaches_end"] = station_stats["end"] >= (global_end - pd.Timedelta(days=7))

# rule 2: must have at least 3 months of REAL observations
station_stats[">=3_months_data"] = station_stats["n_hours"] >= 90 * 24

# final filter
valid_stations = station_stats[
    station_stats["reaches_end"] &
    station_stats[">=3_months_data"]
].index

df = df[df["eic_code"].isin(valid_stations)].copy()

print(f"Stations after dropping: {len(df['eic_code'].unique())}, rows: {len(df)}")

Stations before dropping: 411, rows: 5416753
Stations after dropping: 395, rows: 5307320

In [132]:
prices_df = pd.read_excel('data/additional_data/ВхідніДані.xlsx', sheet_name="Prices", header=1)
cols_to_rename = {
    'Row Labels': 'Date/Hour',
    'БР- (продаж)': 'selling_price',
    'БР+ (купівля)': 'buying price',
    'РДН': 'day_ahead_price'
}
prices_df = prices_df.rename(columns=cols_to_rename).copy()
prices_df

                 Date/Hour  selling_price  buying price  day_ahead_price
0      2024-01-01 00:00:00            NaN           NaN              NaN
1                        1   1.000000e-02  5.985000e+01     5.700000e+01
2                        2   1.000000e-02  5.985000e+01     5.700000e+01
3                        3   1.000000e-02  5.833000e+01     5.555000e+01
4                        4   1.000000e-02  3.990000e+01     3.800000e+01
...                    ...            ...           ...              ...
21020                   21            NaN           NaN     1.497480e+04
21021                   22            NaN           NaN     1.494790e+04
21022                   23            NaN           NaN     1.298600e+04
21023                   24            NaN           NaN     6.900000e+03
21024          Grand Total   7.033448e+07  1.456568e+08     1.064864e+08

[21025 rows x 4 columns]

In [133]:
# identify rows that contain full datetime
is_datetime = prices_df['Date/Hour'].astype(str).str.contains('-')

# extract base date
prices_df.loc[is_datetime, 'base_date'] = pd.to_datetime(prices_df.loc[is_datetime, 'Date/Hour'])

# forward fill the date
prices_df['base_date'] = prices_df['base_date'].ffill()

# extract hour rows
prices_df['hour'] = pd.to_numeric(prices_df['Date/Hour'], errors='coerce')

# build final datetime
prices_df['datetime'] = prices_df['base_date']

# where hour exists → add (hour-1)
mask = prices_df['hour'].notna()
prices_df.loc[mask, 'datetime'] = (
    prices_df.loc[mask, 'base_date'] +
    pd.to_timedelta(prices_df.loc[mask, 'hour'] - 1, unit='h')
)

# drop helper columns if you want
prices_df = prices_df.drop(columns=['base_date', 'hour', 'Date/Hour'])
prices_df.dropna(inplace=True)
prices_df

       selling_price  buying price  day_ahead_price            datetime
1       1.000000e-02  5.985000e+01     5.700000e+01 2024-01-01 00:00:00
2       1.000000e-02  5.985000e+01     5.700000e+01 2024-01-01 01:00:00
3       1.000000e-02  5.833000e+01     5.555000e+01 2024-01-01 02:00:00
4       1.000000e-02  3.990000e+01     3.800000e+01 2024-01-01 03:00:00
5       1.000000e-02  3.360000e+01     3.200000e+01 2024-01-01 04:00:00
...              ...           ...              ...                 ...
20520   1.163180e+04  1.679843e+04     1.224400e+04 2026-03-31 20:00:00
20521   1.000000e-02  1.281105e+04     1.220100e+04 2026-03-31 21:00:00
20522   1.000000e-02  1.018290e+04     9.698000e+03 2026-03-31 22:00:00
20523   4.500000e-01  8.608950e+03     8.199000e+03 2026-03-31 23:00:00
21024   7.033448e+07  1.456568e+08     1.064864e+08 2026-04-20 00:00:00

[19702 rows x 4 columns]

In [134]:
full_range = pd.date_range(prices_df['datetime'].min(),
prices_df['datetime'].max(), freq='h')
prices_df = (
  prices_df
  .set_index('datetime')
  .reindex(full_range)
  .ffill()  # carry previous hour's price into the phantom hour
  .reset_index()
  .rename(columns={'index': 'datetime'})
)

In [135]:
df = df.merge(prices_df, on='datetime', how='left', suffixes=('', '_dict'))
df

,eic_code,datetime,sum_of_kWh,dist_price,elect_price,station_type,oblast,latitude,longitude,osr_desc,address,max_power,max_solar,selling_price,buying price,day_ahead_price
0,62Z0008583037334,2024-09-01 01:00:00,19.264333,2.15221,5.60000,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,25.52,3781.00,6930.00,3980.00
1,62Z0008583037334,2024-09-01 02:00:00,16.892233,2.15221,3.98000,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,25.52,9.33,3150.00,3000.00
2,62Z0008583037334,2024-09-01 03:00:00,15.382714,2.15221,3.00000,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,25.52,1377.50,6930.00,1450.00
3,62Z0008583037334,2024-09-01 04:00:00,15.598360,2.15221,1.45000,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,25.52,950.00,6930.00,1000.00
4,62Z0008583037334,2024-09-01 05:00:00,14.735777,2.15221,1.00000,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,25.52,9.32,3015.60,2872.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5307315,62Z9997819406173,2025-08-31 20:00:00,22.540932,1.76339,14.89963,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,15.00,14156.98,16799.92,14902.08
5307316,62Z9997819406173,2025-08-31 21:00:00,24.207382,1.76339,14.90208,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,15.00,14155.97,16799.91,14901.02
5307317,62Z9997819406173,2025-08-31 22:00:00,25.211150,1.76339,14.90102,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,15.00,4.47,15643.03,14898.12
5307318,62Z9997819406173,2025-08-31 23:00:00,22.579913,1.76339,14.89812,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,15.00,0.03,7024.50,6690.00
5307319,62Z9997819406173,2025-09-01 00:00:00,19.783005,1.76339,6.69000,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,15.00,0.01,5449.50,5190.00

In [26]:
path = "data/bronze/no_weather.parquet"
weather_path = "data/bronze/with_weather.parquet"
checkpoint_path = "data/bronze/checkpoint.parquet"

In [141]:
df.drop(columns=['dist_price', 'elect_price'], inplace=True)

In [143]:
df.to_parquet(path, index=False)
df.to_parquet(checkpoint_path, index=False)
df

,eic_code,datetime,sum_of_kWh,station_type,oblast,latitude,longitude,osr_desc,address,max_power,max_solar,selling_price,buying price,day_ahead_price
0,62Z0008583037334,2024-09-01 01:00:00,19.264333,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,25.52,3781.00,6930.00,3980.00
1,62Z0008583037334,2024-09-01 02:00:00,16.892233,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,25.52,9.33,3150.00,3000.00
2,62Z0008583037334,2024-09-01 03:00:00,15.382714,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,25.52,1377.50,6930.00,1450.00
3,62Z0008583037334,2024-09-01 04:00:00,15.598360,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,25.52,950.00,6930.00,1000.00
4,62Z0008583037334,2024-09-01 05:00:00,14.735777,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,25.52,9.32,3015.60,2872.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5307315,62Z9997819406173,2025-08-31 20:00:00,22.540932,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,15.00,14156.98,16799.92,14902.08
5307316,62Z9997819406173,2025-08-31 21:00:00,24.207382,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,15.00,14155.97,16799.91,14901.02
5307317,62Z9997819406173,2025-08-31 22:00:00,25.211150,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,15.00,4.47,15643.03,14898.12
5307318,62Z9997819406173,2025-08-31 23:00:00,22.579913,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,15.00,0.03,7024.50,6690.00
5307319,62Z9997819406173,2025-09-01 00:00:00,19.783005,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,15.00,0.01,5449.50,5190.00

In [150]:
from weather import smart_requests

df_with_weather = smart_requests(
    path_in=checkpoint_path,
    path_out=weather_path,
    checkpoint_path=checkpoint_path,
    eic_code_name='eic_code',
    lat_col='latitude',
    lon_col='longitude',
)
df_with_weather

Gas stations with weather: 299
Gas stations with no weather: 96

Gas stations:   0%|          | 0/96 [00:00<?, ?it/s]

<Response [429]>
429
{"reason":"Daily API request limit exceeded. Please try again tomorrow.","error":true}

Stopping now

,eic_code,datetime,sum_of_kWh,station_type,oblast,latitude,longitude,osr_desc,address,max_power,...,cloud_cover_high,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,direct_normal_irradiance,diffuse_radiation,precipitation,rain,snowfall
0,62Z0008583037334,2024-09-01 01:00:00+03:00,19.264333,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,...,25.0,10.4,360.0,19.1,0.0,0.0,0.0,0.0,0.0,0.0
1,62Z0008583037334,2024-09-01 02:00:00+03:00,16.892233,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,...,27.0,13.4,336.0,22.3,0.0,0.0,0.0,0.0,0.0,0.0
2,62Z0008583037334,2024-09-01 03:00:00+03:00,15.382714,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,...,45.0,13.6,338.0,23.4,0.0,0.0,0.0,0.0,0.0,0.0
3,62Z0008583037334,2024-09-01 04:00:00+03:00,15.598360,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,...,22.0,12.1,323.0,19.4,0.0,0.0,0.0,0.0,0.0,0.0
4,62Z0008583037334,2024-09-01 05:00:00+03:00,14.735777,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,...,26.0,15.0,325.0,25.2,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5307315,62Z9997819406173,2025-08-31 23:00:00+03:00,22.540932,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5307316,62Z9997819406173,2025-09-01 00:00:00+03:00,24.207382,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5307317,62Z9997819406173,2025-09-01 01:00:00+03:00,25.211150,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5307318,62Z9997819406173,2025-09-01 02:00:00+03:00,22.579913,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5307319,62Z9997819406173,2025-09-01 03:00:00+03:00,19.783005,ОККО-міська,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283",80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# df_with_weather = pd.read_parquet(weather_path)
# df_with_weather

,eic_code,datetime,sum_of_kWh,station_type,oblast,latitude,longitude,osr_desc,address,max_power,...,cloud_cover_high,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,direct_normal_irradiance,diffuse_radiation,precipitation,rain,snowfall
0,62Z0008583037334,2024-09-01 01:00:00+03:00,19.264333,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,...,25.0,10.4,360.0,19.1,0.0,0.0,0.0,0.0,0.0,0.0
1,62Z0008583037334,2024-09-01 02:00:00+03:00,16.892233,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,...,27.0,13.4,336.0,22.3,0.0,0.0,0.0,0.0,0.0,0.0
2,62Z0008583037334,2024-09-01 03:00:00+03:00,15.382714,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,...,45.0,13.6,338.0,23.4,0.0,0.0,0.0,0.0,0.0,0.0
3,62Z0008583037334,2024-09-01 04:00:00+03:00,15.598360,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,...,22.0,12.1,323.0,19.4,0.0,0.0,0.0,0.0,0.0,0.0
4,62Z0008583037334,2024-09-01 05:00:00+03:00,14.735777,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,...,26.0,15.0,325.0,25.2,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2852,62Z9512175266041,2025-08-31 23:00:00+03:00,26.379837,ОККО-стандарт,м. Київ,50.403745,30.684027,Київ,"м. Київ, Харківське шосе, 203",27.0,...,0.0,10.0,36.0,20.5,0.0,0.0,0.0,0.0,0.0,0.0
2853,62Z9512175266041,2025-09-01 00:00:00+03:00,27.803749,ОККО-стандарт,м. Київ,50.403745,30.684027,Київ,"м. Київ, Харківське шосе, 203",27.0,...,0.0,9.5,37.0,19.1,0.0,0.0,0.0,0.0,0.0,0.0
2854,62Z9512175266041,2025-09-01 01:00:00+03:00,27.429035,ОККО-стандарт,м. Київ,50.403745,30.684027,Київ,"м. Київ, Харківське шосе, 203",27.0,...,0.0,9.0,35.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0
2855,62Z9512175266041,2025-09-01 02:00:00+03:00,25.068339,ОККО-стандарт,м. Київ,50.403745,30.684027,Київ,"м. Київ, Харківське шосе, 203",27.0,...,0.0,7.1,43.0,16.9,0.0,0.0,0.0,0.0,0.0,0.0
2856,62Z9512175266041,2025-09-01 03:00:00+03:00,21.321203,ОККО-стандарт,м. Київ,50.403745,30.684027,Київ,"м. Київ, Харківське шосе, 203",27.0,...,1.0,6.9,33.0,13.3,0.0,0.0,0.0,0.0,0.0,0.0

In [33]:
def find_missing_timesteps(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    GLOBAL_MIN_DT = df["datetime"].min()
    df["time_idx"] = (
        (df["datetime"] - GLOBAL_MIN_DT).dt.total_seconds() / 3600
    ).astype(int)
    for grp, gdf in df.groupby("eic_code"):
        full_range = set(range(gdf["time_idx"].min(), gdf["time_idx"].max() + 1))
        present    = set(gdf["time_idx"].values)
        missing    = sorted(full_range - present)
        if missing:
            rows.append({"eic_code": grp, "missing_count": len(missing), "missing_time_idx": missing})
    if not rows:
        return pd.DataFrame(columns=["eic_code", "missing_count", "missing_time_idx"])
    return pd.DataFrame(rows).sort_values("missing_count", ascending=False).reset_index(drop=True)

missing = find_missing_timesteps(df_with_weather)
missing

0     62Z904708724460A
1     62Z3307823675943
2     62Z3816201773292
3     62Z9342951787758
4     62Z6057805565288
5     62Z1291599260160
6     62Z6153652780082
7     62Z3831028766926
8     62Z1105854285450
9     62Z0188778556192
10    62Z5064314448909
11    62Z0232888687220
12    62Z3914112748257
Name: eic_code, dtype: object

In [9]:
static_data_dict = pd.read_excel("data/raw/8month2025.xlsx", sheet_name="Dict")[['EIC-код', 'Унікод']]
static_data_dict

              EIC-код    Унікод
0    62Z3386096691495  40110200
1    62Z5700239654314  40110500
2    62Z8292498523912  40110700
3    62Z6337618908569  40111000
4    62Z1180469265339  40111100
..                ...       ...
424  62Z2673921373211  41261600
425  62Z7841956124522  41062200
426  62Z5821574095639  41261800
427  62Z1528625762710  41261400
428  62Z4670013981058  41261300

[429 rows x 2 columns]

In [10]:
ev_data = pd.read_excel("data/additional_data/EV_chargers.xlsx")[['Унікод АЗС', 'Дата запуску', 'Потужність станції, кВт']]
cols_to_rename = {
    'Унікод АЗС': 'Унікод',
    'Дата запуску': 'ev_start',
    'Потужність станції, кВт': 'ev_power'
}
ev_data = ev_data.rename(columns=cols_to_rename).copy()
ev_data

      Унікод   ev_start  ev_power
0   40511100 2021-04-30        50
1   40660600 2021-11-30        50
2   60961300 2022-11-16        50
3   46164000 2023-04-05        50
4   40162800 2023-04-12       150
..       ...        ...       ...
84  40111100 2026-01-09       160
85  40814400 2026-01-27       160
86  40814400 2026-01-27       160
87  40118800 2026-03-17       160
88  40118800 2026-03-17       160

[89 rows x 3 columns]

In [11]:
ev_data = ev_data.merge(static_data_dict, on='Унікод', how='left', suffixes=('', '_dict'))
ev_data.drop(columns=['Унікод'], inplace=True)
ev_data.dropna(inplace=True)
ev_data = ev_data.rename(columns={"EIC-код": "eic_code"})
ev_data = ev_data.sort_values(["eic_code", "ev_start"])
ev_data

     ev_start  ev_power          eic_code
32 2023-09-21       150  62Z0101426517156
34 2023-09-21       120  62Z0101426517156
86 2025-11-12       150  62Z0101426517156
33 2023-09-21       150  62Z013852333354Y
35 2023-09-21       120  62Z013852333354Y
..        ...       ...               ...
94 2026-03-17       160  62Z9492255746718
66 2025-07-11       160  62Z9572466865833
67 2025-07-11       160  62Z9572466865833
19 2023-06-08       150  62Z9972124228553
22 2023-06-08       120  62Z9972124228553

[93 rows x 3 columns]

In [12]:
# ── 3. For each location × datetime row, sum power of chargers installed
#       on or before that datetime.
# ─────────────────────────────────────────────────────────────────────────────
# Strategy: cross-join ev_data onto df_with_weather (on eic_code only),
# filter to rows where ev_start <= datetime, then sum ev_power per row.

# Convert ev_start to UTC so the comparison is tz-consistent
ev_data["ev_start_utc"] = ev_data["ev_start"].dt.tz_localize("UTC")

# Merge on eic_code (inner keeps only locations that have EV chargers)
merged = df_with_weather.merge(
    ev_data[["eic_code", "ev_start_utc", "ev_power"]],
    on="eic_code",
    how="left",   # left keeps all weather rows; NaN where no charger
)
# Keep only chargers that were already installed at the row's datetime
mask_installed = (
    merged["ev_start_utc"].isna() |               # no charger → keep (will sum to 0)
    (merged["ev_start_utc"] <= merged["datetime"])
)
merged = merged[mask_installed]

# Sum ev_power per original row (eic_code + datetime); NaN → 0
max_ev_power = (
    merged
    .groupby(["eic_code", "datetime"], sort=False)["ev_power"]
    .sum()
    .reset_index()
    .rename(columns={"ev_power": "max_ev_power_kW"})
)

# ── 4. Join back and fill locations with no EV chargers with 0 ───────────────
df_result = df_with_weather.merge(max_ev_power, on=["eic_code", "datetime"], how="left")
df_result["max_ev_power_kW"] = df_result["max_ev_power_kW"].fillna(0)
df_result

,eic_code,datetime,sum_of_kWh,station_type,oblast,latitude,longitude,osr_desc,address,max_power,...,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,direct_normal_irradiance,diffuse_radiation,precipitation,rain,snowfall,max_ev_power_kW
0,62Z0008583037334,2024-09-01 01:00:00+03:00,19.264333,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,...,10.4,360.0,19.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,62Z0008583037334,2024-09-01 02:00:00+03:00,16.892233,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,...,13.4,336.0,22.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,62Z0008583037334,2024-09-01 03:00:00+03:00,15.382714,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,...,13.6,338.0,23.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,62Z0008583037334,2024-09-01 04:00:00+03:00,15.598360,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,...,12.1,323.0,19.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,62Z0008583037334,2024-09-01 05:00:00+03:00,14.735777,ОККО-комплекс,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки...",110.0,...,15.0,325.0,25.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5307315,62Z9512175266041,2025-08-31 23:00:00+03:00,26.379837,ОККО-стандарт,м. Київ,50.403745,30.684027,Київ,"м. Київ, Харківське шосе, 203",27.0,...,10.0,36.0,20.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5307316,62Z9512175266041,2025-09-01 00:00:00+03:00,27.803749,ОККО-стандарт,м. Київ,50.403745,30.684027,Київ,"м. Київ, Харківське шосе, 203",27.0,...,9.5,37.0,19.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5307317,62Z9512175266041,2025-09-01 01:00:00+03:00,27.429035,ОККО-стандарт,м. Київ,50.403745,30.684027,Київ,"м. Київ, Харківське шосе, 203",27.0,...,9.0,35.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5307318,62Z9512175266041,2025-09-01 02:00:00+03:00,25.068339,ОККО-стандарт,м. Київ,50.403745,30.684027,Київ,"м. Київ, Харківське шосе, 203",27.0,...,7.1,43.0,16.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5307319,62Z9512175266041,2025-09-01 03:00:00+03:00,21.321203,ОККО-стандарт,м. Київ,50.403745,30.684027,Київ,"м. Київ, Харківське шосе, 203",27.0,...,6.9,33.0,13.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
df_result.to_parquet("data/silver/full_df_weather_prices__power_etc.parquet", index=False)

In [16]:
df_result[df_result['max_ev_power_kW'] > 0][df_result['max_solar'] > 0]

/var/folders/5w/bchvy66s6vbgncfkws1skvf40000gp/T/ipykernel_4334/1891919442.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_result[df_result['max_ev_power_kW'] > 0][df_result['max_solar'] > 0]

,eic_code,datetime,sum_of_kWh,station_type,oblast,latitude,longitude,osr_desc,address,max_power,...,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,direct_normal_irradiance,diffuse_radiation,precipitation,rain,snowfall,max_ev_power_kW
43845,62Z013852333354Y,2024-09-01 01:00:00+03:00,58.544524,ОККО-комплекс,Черкаська,48.566059,30.230684,Черкаси,"Уманський р-н, с/р Фурманська, автодорога Київ...",514.0,...,12.7,25.0,23.4,0.0,0.0,0.0,0.0,0.0,0.0,270.0
43846,62Z013852333354Y,2024-09-01 02:00:00+03:00,48.709044,ОККО-комплекс,Черкаська,48.566059,30.230684,Черкаси,"Уманський р-н, с/р Фурманська, автодорога Київ...",514.0,...,11.0,23.0,22.7,0.0,0.0,0.0,0.0,0.0,0.0,270.0
43847,62Z013852333354Y,2024-09-01 03:00:00+03:00,44.025482,ОККО-комплекс,Черкаська,48.566059,30.230684,Черкаси,"Уманський р-н, с/р Фурманська, автодорога Київ...",514.0,...,10.1,17.0,19.1,0.0,0.0,0.0,0.0,0.0,0.0,270.0
43848,62Z013852333354Y,2024-09-01 04:00:00+03:00,40.746989,ОККО-комплекс,Черкаська,48.566059,30.230684,Черкаси,"Уманський р-н, с/р Фурманська, автодорога Київ...",514.0,...,11.1,25.0,19.1,0.0,0.0,0.0,0.0,0.0,0.0,270.0
43849,62Z013852333354Y,2024-09-01 05:00:00+03:00,44.962195,ОККО-комплекс,Черкаська,48.566059,30.230684,Черкаси,"Уманський р-н, с/р Фурманська, автодорога Київ...",514.0,...,11.4,28.0,20.2,0.0,0.0,0.0,0.0,0.0,0.0,270.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5286965,62Z9042463861989,2025-08-31 23:00:00+03:00,23.000000,ОККО-міська,м. Київ,50.353642,30.492940,Київ,"м. Київ, вул. Академіка Заболотного, 25",170.0,...,10.0,26.0,16.6,0.0,0.0,0.0,0.0,0.0,0.0,160.0
5286966,62Z9042463861989,2025-09-01 00:00:00+03:00,63.000000,ОККО-міська,м. Київ,50.353642,30.492940,Київ,"м. Київ, вул. Академіка Заболотного, 25",170.0,...,9.5,29.0,16.9,0.0,0.0,0.0,0.0,0.0,0.0,160.0
5286967,62Z9042463861989,2025-09-01 01:00:00+03:00,38.000000,ОККО-міська,м. Київ,50.353642,30.492940,Київ,"м. Київ, вул. Академіка Заболотного, 25",170.0,...,6.4,45.0,15.8,0.0,0.0,0.0,0.0,0.0,0.0,160.0
5286968,62Z9042463861989,2025-09-01 02:00:00+03:00,23.000000,ОККО-міська,м. Київ,50.353642,30.492940,Київ,"м. Київ, вул. Академіка Заболотного, 25",170.0,...,5.7,37.0,8.6,0.0,0.0,0.0,0.0,0.0,0.0,160.0
5286969,62Z9042463861989,2025-09-01 03:00:00+03:00,23.000000,ОККО-міська,м. Київ,50.353642,30.492940,Київ,"м. Київ, вул. Академіка Заболотного, 25",170.0,...,6.2,26.0,9.7,0.0,0.0,0.0,0.0,0.0,0.0,160.0

In [1]:
import pandas as pd

df_result = pd.read_parquet("data/silver/full_df_weather_prices__power_etc.parquet")

In [2]:
df_gold = df_result[[
    'eic_code', 'datetime', 'sum_of_kWh',
    'day_ahead_price', 'selling_price', 'buying price',
    'max_power', 'max_solar', 'max_ev_power_kW',
    'latitude', 'longitude', 'osr_desc', 'station_type', 'oblast',
    'temperature_2m', 'relative_humidity_2m', 'dew_point_2m',
    'apparent_temperature', 'surface_pressure', 'cloud_cover',
    'cloud_cover_low', 'cloud_cover_mid', 'cloud_cover_high',
    'wind_speed_10m', 'wind_direction_10m', 'wind_gusts_10m',
    'shortwave_radiation', 'direct_normal_irradiance', 'diffuse_radiation',
    'precipitation', 'rain', 'snowfall',
]]

cols_to_rename = {
    'day_ahead_price': 'dam_price',
    'selling_price': 'sell_bm_price',
    'buying price': 'buy_bm_price',
    'max_power': 'max_power',
    'max_solar': 'max_solar',
    'max_ev_power_kW': 'max_ev',
    'osr_desc': 'dso_desc',
}

df_gold = df_gold.rename(columns=cols_to_rename)
df_gold

,eic_code,datetime,sum_of_kWh,dam_price,sell_bm_price,buy_bm_price,max_power,max_solar,max_ev,latitude,...,cloud_cover_high,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,direct_normal_irradiance,diffuse_radiation,precipitation,rain,snowfall
0,62Z0008583037334,2024-09-01 01:00:00+03:00,19.264333,3980.00,3781.00,6930.00,110.0,25.52,0.0,48.442430,...,25.0,10.4,360.0,19.1,0.0,0.0,0.0,0.0,0.0,0.0
1,62Z0008583037334,2024-09-01 02:00:00+03:00,16.892233,3000.00,9.33,3150.00,110.0,25.52,0.0,48.442430,...,27.0,13.4,336.0,22.3,0.0,0.0,0.0,0.0,0.0,0.0
2,62Z0008583037334,2024-09-01 03:00:00+03:00,15.382714,1450.00,1377.50,6930.00,110.0,25.52,0.0,48.442430,...,45.0,13.6,338.0,23.4,0.0,0.0,0.0,0.0,0.0,0.0
3,62Z0008583037334,2024-09-01 04:00:00+03:00,15.598360,1000.00,950.00,6930.00,110.0,25.52,0.0,48.442430,...,22.0,12.1,323.0,19.4,0.0,0.0,0.0,0.0,0.0,0.0
4,62Z0008583037334,2024-09-01 05:00:00+03:00,14.735777,2872.00,9.32,3015.60,110.0,25.52,0.0,48.442430,...,26.0,15.0,325.0,25.2,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5307315,62Z9512175266041,2025-08-31 23:00:00+03:00,26.379837,14902.08,14156.98,16799.92,27.0,15.00,0.0,50.403745,...,0.0,10.0,36.0,20.5,0.0,0.0,0.0,0.0,0.0,0.0
5307316,62Z9512175266041,2025-09-01 00:00:00+03:00,27.803749,14901.02,14155.97,16799.91,27.0,15.00,0.0,50.403745,...,0.0,9.5,37.0,19.1,0.0,0.0,0.0,0.0,0.0,0.0
5307317,62Z9512175266041,2025-09-01 01:00:00+03:00,27.429035,14898.12,4.47,15643.03,27.0,15.00,0.0,50.403745,...,0.0,9.0,35.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0
5307318,62Z9512175266041,2025-09-01 02:00:00+03:00,25.068339,6690.00,0.03,7024.50,27.0,15.00,0.0,50.403745,...,0.0,7.1,43.0,16.9,0.0,0.0,0.0,0.0,0.0,0.0
5307319,62Z9512175266041,2025-09-01 03:00:00+03:00,21.321203,5190.00,0.01,5449.50,27.0,15.00,0.0,50.403745,...,1.0,6.9,33.0,13.3,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
def add_calendar_features(df: pd.DataFrame) -> pd.DataFrame:
    df["datetime"]        = pd.to_datetime(df["datetime"])
    df["Month"]       = df["datetime"].dt.month.astype(str)
    df["Day"]         = df["datetime"].dt.day.astype(str)
    df["Hour"]        = df["datetime"].dt.hour.astype(str)
    df["day_of_week"] = df["datetime"].dt.dayofweek.astype(str)
    season_map = {
        12: "winter", 1: "winter", 2: "winter",
        3: "spring",  4: "spring", 5: "spring",
        6: "summer",  7: "summer", 8: "summer",
        9: "autumn", 10: "autumn", 11: "autumn",
    }
    df["season"] = df["datetime"].dt.month.map(season_map)
    return df

df_gold = add_calendar_features(df_gold)
df_gold

,eic_code,datetime,sum_of_kWh,dam_price,sell_bm_price,buy_bm_price,max_power,max_solar,max_ev,latitude,...,direct_normal_irradiance,diffuse_radiation,precipitation,rain,snowfall,Month,Day,Hour,day_of_week,season
0,62Z0008583037334,2024-09-01 01:00:00+03:00,19.264333,3980.00,3781.00,6930.00,110.0,25.52,0.0,48.442430,...,0.0,0.0,0.0,0.0,0.0,9,1,1,6,autumn
1,62Z0008583037334,2024-09-01 02:00:00+03:00,16.892233,3000.00,9.33,3150.00,110.0,25.52,0.0,48.442430,...,0.0,0.0,0.0,0.0,0.0,9,1,2,6,autumn
2,62Z0008583037334,2024-09-01 03:00:00+03:00,15.382714,1450.00,1377.50,6930.00,110.0,25.52,0.0,48.442430,...,0.0,0.0,0.0,0.0,0.0,9,1,3,6,autumn
3,62Z0008583037334,2024-09-01 04:00:00+03:00,15.598360,1000.00,950.00,6930.00,110.0,25.52,0.0,48.442430,...,0.0,0.0,0.0,0.0,0.0,9,1,4,6,autumn
4,62Z0008583037334,2024-09-01 05:00:00+03:00,14.735777,2872.00,9.32,3015.60,110.0,25.52,0.0,48.442430,...,0.0,0.0,0.0,0.0,0.0,9,1,5,6,autumn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5307315,62Z9512175266041,2025-08-31 23:00:00+03:00,26.379837,14902.08,14156.98,16799.92,27.0,15.00,0.0,50.403745,...,0.0,0.0,0.0,0.0,0.0,8,31,23,6,summer
5307316,62Z9512175266041,2025-09-01 00:00:00+03:00,27.803749,14901.02,14155.97,16799.91,27.0,15.00,0.0,50.403745,...,0.0,0.0,0.0,0.0,0.0,9,1,0,0,autumn
5307317,62Z9512175266041,2025-09-01 01:00:00+03:00,27.429035,14898.12,4.47,15643.03,27.0,15.00,0.0,50.403745,...,0.0,0.0,0.0,0.0,0.0,9,1,1,0,autumn
5307318,62Z9512175266041,2025-09-01 02:00:00+03:00,25.068339,6690.00,0.03,7024.50,27.0,15.00,0.0,50.403745,...,0.0,0.0,0.0,0.0,0.0,9,1,2,0,autumn
5307319,62Z9512175266041,2025-09-01 03:00:00+03:00,21.321203,5190.00,0.01,5449.50,27.0,15.00,0.0,50.403745,...,0.0,0.0,0.0,0.0,0.0,9,1,3,0,autumn

In [4]:
GLOBAL_MIN_DT = None

def build_time_index(df: pd.DataFrame) -> pd.DataFrame:
    global GLOBAL_MIN_DT
    # df["datetime"] = pd.to_datetime(df["datetime"])
    # if GLOBAL_MIN_DT is None:
    #     GLOBAL_MIN_DT = df["datetime"].min()
    # df['datetime'] = df['datetime'].dt.tz_convert('UTC')

    df = df.sort_values(['eic_code', 'datetime'])

    df['time_idx'] = (
        (df['datetime'] - df['datetime'].min())
        .dt.total_seconds() // 3600
    ).astype(int)
    return df

df_gold = build_time_index(df_gold)
df_gold

,eic_code,datetime,sum_of_kWh,dam_price,sell_bm_price,buy_bm_price,max_power,max_solar,max_ev,latitude,...,diffuse_radiation,precipitation,rain,snowfall,Month,Day,Hour,day_of_week,season,time_idx
8783,62Z0008583037334,2024-01-01 01:00:00+02:00,24.043645,57.00,0.01,59.85,110.0,25.52,0.0,48.442430,...,0.0,0.0,0.0,0.0,1,1,1,0,winter,0
8784,62Z0008583037334,2024-01-01 02:00:00+02:00,22.768120,55.55,0.01,58.33,110.0,25.52,0.0,48.442430,...,0.0,0.1,0.1,0.0,1,1,2,0,winter,1
8785,62Z0008583037334,2024-01-01 03:00:00+02:00,21.620148,38.00,0.01,39.90,110.0,25.52,0.0,48.442430,...,0.0,0.2,0.2,0.0,1,1,3,0,winter,2
8786,62Z0008583037334,2024-01-01 04:00:00+02:00,20.791056,32.00,0.01,33.60,110.0,25.52,0.0,48.442430,...,0.0,0.1,0.1,0.0,1,1,4,0,winter,3
8787,62Z0008583037334,2024-01-01 05:00:00+02:00,20.344623,30.00,2.27,31.50,110.0,25.52,0.0,48.442430,...,0.0,0.1,0.1,0.0,1,1,5,0,winter,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5048681,62Z9997819406173,2025-08-31 23:00:00+03:00,22.540932,14902.08,14156.98,16799.92,80.0,15.00,0.0,49.800007,...,0.0,0.0,0.0,0.0,8,31,23,6,summer,14613
5048682,62Z9997819406173,2025-09-01 00:00:00+03:00,24.207382,14901.02,14155.97,16799.91,80.0,15.00,0.0,49.800007,...,0.0,0.0,0.0,0.0,9,1,0,0,autumn,14614
5048683,62Z9997819406173,2025-09-01 01:00:00+03:00,25.211150,14898.12,4.47,15643.03,80.0,15.00,0.0,49.800007,...,0.0,0.0,0.0,0.0,9,1,1,0,autumn,14615
5048684,62Z9997819406173,2025-09-01 02:00:00+03:00,22.579913,6690.00,0.03,7024.50,80.0,15.00,0.0,49.800007,...,0.0,0.0,0.0,0.0,9,1,2,0,autumn,14616
5048685,62Z9997819406173,2025-09-01 03:00:00+03:00,19.783005,5190.00,0.01,5449.50,80.0,15.00,0.0,49.800007,...,0.0,0.0,0.0,0.0,9,1,3,0,autumn,14617

In [5]:
def find_missing_timesteps(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for grp, gdf in df.groupby("eic_code"):
        full_range = set(range(gdf["time_idx"].min(), gdf["time_idx"].max() + 1))
        present    = set(gdf["time_idx"].values)
        missing    = sorted(full_range - present)
        if missing:
            rows.append({"eic_code": grp, "missing_count": len(missing), "missing_time_idx": missing})
    if not rows:
        return pd.DataFrame(columns=["eic_code", "missing_count", "missing_time_idx"])
    return pd.DataFrame(rows).sort_values("missing_count", ascending=False).reset_index(drop=True)

missing = find_missing_timesteps(df_gold)
missing

,eic_code,missing_count,missing_time_idx
0,62Z904708724460A,5858,"[2165, 2186, 2187, 2188, 2189, 2190, 2191, 219..."
1,62Z3307823675943,1489,"[1442, 1443, 1444, 1445, 1446, 1447, 1448, 144..."
2,62Z3816201773292,747,"[2165, 7201, 8786, 8787, 8788, 8789, 8790, 879..."
3,62Z9342951787758,747,"[2165, 7201, 8042, 8043, 8044, 8045, 8046, 804..."
4,62Z6057805565288,747,"[2165, 4370, 4371, 4372, 4373, 4374, 4375, 437..."
...,...,...,...
385,62Z8916686891448,1,[10901]
386,62Z5197867294689,1,[10901]
387,62Z1108084147506,1,[10901]
388,62Z9042463861989,1,[10901]
389,62Z0008583037334,1,[7201]

In [6]:
def get_longest_uninterrupted_from_end(gdf: pd.DataFrame, min_days: int = 90):
    gdf = gdf.sort_values("datetime").reset_index(drop=True)
    deltas = gdf["datetime"].diff()
    gap_positions = deltas[deltas > pd.Timedelta("1h")].index.tolist()
    last_gap = gap_positions[-1] if gap_positions else 0
    clean_block = gdf.iloc[last_gap:]
    if (clean_block["datetime"].max() - clean_block["datetime"].min()).days < min_days:
        return None
    return clean_block

significantly_missing = missing[missing["missing_count"] > 3]["eic_code"].tolist()

kept, dropped = [], []
for eic in significantly_missing:
    result = get_longest_uninterrupted_from_end(df_gold[df_gold["eic_code"] == eic])
    if result is None:
        dropped.append(eic)
    else:
        kept.append(result)

clean_others = df_gold[~df_gold["eic_code"].isin(significantly_missing)]
df_gold = pd.concat([clean_others] + kept, ignore_index=True).sort_values(
    ["eic_code", "datetime"]
).reset_index(drop=True)
df_gold = df_gold[~df_gold["eic_code"].isin(dropped)].reset_index(drop=True)

print(f"Trimmed : {len(significantly_missing)} stations")
print(f"Kept    : {len(kept)}")
print(f"Dropped : {len(dropped)}")
print(f"Remaining stations : {df_gold['eic_code'].nunique()}")
print(f"Remaining rows     : {len(df_gold):,}")
df_gold

Trimmed : 14 stations
Kept    : 14
Dropped : 0
Remaining stations : 395
Remaining rows     : 5,175,098

,eic_code,datetime,sum_of_kWh,dam_price,sell_bm_price,buy_bm_price,max_power,max_solar,max_ev,latitude,...,diffuse_radiation,precipitation,rain,snowfall,Month,Day,Hour,day_of_week,season,time_idx
0,62Z0008583037334,2024-01-01 01:00:00+02:00,24.043645,57.00,0.01,59.85,110.0,25.52,0.0,48.442430,...,0.0,0.0,0.0,0.0,1,1,1,0,winter,0
1,62Z0008583037334,2024-01-01 02:00:00+02:00,22.768120,55.55,0.01,58.33,110.0,25.52,0.0,48.442430,...,0.0,0.1,0.1,0.0,1,1,2,0,winter,1
2,62Z0008583037334,2024-01-01 03:00:00+02:00,21.620148,38.00,0.01,39.90,110.0,25.52,0.0,48.442430,...,0.0,0.2,0.2,0.0,1,1,3,0,winter,2
3,62Z0008583037334,2024-01-01 04:00:00+02:00,20.791056,32.00,0.01,33.60,110.0,25.52,0.0,48.442430,...,0.0,0.1,0.1,0.0,1,1,4,0,winter,3
4,62Z0008583037334,2024-01-01 05:00:00+02:00,20.344623,30.00,2.27,31.50,110.0,25.52,0.0,48.442430,...,0.0,0.1,0.1,0.0,1,1,5,0,winter,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5175093,62Z9997819406173,2025-08-31 23:00:00+03:00,22.540932,14902.08,14156.98,16799.92,80.0,15.00,0.0,49.800007,...,0.0,0.0,0.0,0.0,8,31,23,6,summer,14613
5175094,62Z9997819406173,2025-09-01 00:00:00+03:00,24.207382,14901.02,14155.97,16799.91,80.0,15.00,0.0,49.800007,...,0.0,0.0,0.0,0.0,9,1,0,0,autumn,14614
5175095,62Z9997819406173,2025-09-01 01:00:00+03:00,25.211150,14898.12,4.47,15643.03,80.0,15.00,0.0,49.800007,...,0.0,0.0,0.0,0.0,9,1,1,0,autumn,14615
5175096,62Z9997819406173,2025-09-01 02:00:00+03:00,22.579913,6690.00,0.03,7024.50,80.0,15.00,0.0,49.800007,...,0.0,0.0,0.0,0.0,9,1,2,0,autumn,14616
5175097,62Z9997819406173,2025-09-01 03:00:00+03:00,19.783005,5190.00,0.01,5449.50,80.0,15.00,0.0,49.800007,...,0.0,0.0,0.0,0.0,9,1,3,0,autumn,14617

In [7]:
prices_df = pd.read_excel('data/additional_data/ВхідніДані.xlsx', sheet_name="Prices", header=1)
cols_to_rename = {
    'Row Labels': 'datetime',
    'БР- (продаж)': 'sell_bm_price',
    'БР+ (купівля)': 'buy_bm_price',
    'РДН': 'dam_price'
}
prices_df = prices_df.rename(columns=cols_to_rename).copy()

# identify rows that contain full datetime
is_datetime = prices_df['datetime'].astype(str).str.contains('-')

# extract base date
prices_df.loc[is_datetime, 'base_date'] = pd.to_datetime(prices_df.loc[is_datetime, 'datetime'])

# forward fill the date
prices_df['base_date'] = prices_df['base_date'].ffill()

# extract hour rows
prices_df['hour'] = pd.to_numeric(prices_df['datetime'], errors='coerce')

# build final datetime
prices_df['datetime'] = prices_df['base_date']

# where hour exists → add (hour-1)
mask = prices_df['hour'].notna()
prices_df.loc[mask, 'datetime'] = (
    prices_df.loc[mask, 'base_date'] +
    pd.to_timedelta(prices_df.loc[mask, 'hour'] - 1, unit='h')
)
prices_df['datetime'] = prices_df['datetime'].dt.tz_localize(
    "Europe/Kyiv",
    ambiguous="NaT"
)
# drop helper columns if you want
prices_df = prices_df.drop(columns=['base_date', 'hour'])
prices_df.dropna(inplace=True)
df_gold.drop(columns=['sell_bm_price', 'buy_bm_price', 'dam_price'], inplace=True)
df_gold = df_gold.merge(prices_df, on='datetime', how='left', suffixes=('', '_dict'))
df_gold

,eic_code,datetime,sum_of_kWh,max_power,max_solar,max_ev,latitude,longitude,dso_desc,station_type,...,snowfall,Month,Day,Hour,day_of_week,season,time_idx,sell_bm_price,buy_bm_price,dam_price
0,62Z0008583037334,2024-01-01 01:00:00+02:00,24.043645,110.0,25.52,0.0,48.442430,22.192190,Ужгород,ОККО-комплекс,...,0.0,1,1,1,0,winter,0,0.01,59.85,57.00
1,62Z0008583037334,2024-01-01 02:00:00+02:00,22.768120,110.0,25.52,0.0,48.442430,22.192190,Ужгород,ОККО-комплекс,...,0.0,1,1,2,0,winter,1,0.01,58.33,55.55
2,62Z0008583037334,2024-01-01 03:00:00+02:00,21.620148,110.0,25.52,0.0,48.442430,22.192190,Ужгород,ОККО-комплекс,...,0.0,1,1,3,0,winter,2,0.01,39.90,38.00
3,62Z0008583037334,2024-01-01 04:00:00+02:00,20.791056,110.0,25.52,0.0,48.442430,22.192190,Ужгород,ОККО-комплекс,...,0.0,1,1,4,0,winter,3,0.01,33.60,32.00
4,62Z0008583037334,2024-01-01 05:00:00+02:00,20.344623,110.0,25.52,0.0,48.442430,22.192190,Ужгород,ОККО-комплекс,...,0.0,1,1,5,0,winter,4,2.27,31.50,30.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5175093,62Z9997819406173,2025-08-31 23:00:00+03:00,22.540932,80.0,15.00,0.0,49.800007,24.068964,Львів,ОККО-міська,...,0.0,8,31,23,6,summer,14613,0.03,7024.50,6690.00
5175094,62Z9997819406173,2025-09-01 00:00:00+03:00,24.207382,80.0,15.00,0.0,49.800007,24.068964,Львів,ОККО-міська,...,0.0,9,1,0,0,autumn,14614,0.01,5449.50,5190.00
5175095,62Z9997819406173,2025-09-01 01:00:00+03:00,25.211150,80.0,15.00,0.0,49.800007,24.068964,Львів,ОККО-міська,...,0.0,9,1,1,0,autumn,14615,2802.50,6425.42,2950.00
5175096,62Z9997819406173,2025-09-01 02:00:00+03:00,22.579913,80.0,15.00,0.0,49.800007,24.068964,Львів,ОККО-міська,...,0.0,9,1,2,0,autumn,14616,0.01,829.50,790.00
5175097,62Z9997819406173,2025-09-01 03:00:00+03:00,19.783005,80.0,15.00,0.0,49.800007,24.068964,Львів,ОККО-міська,...,0.0,9,1,3,0,autumn,14617,0.01,829.50,790.00

In [8]:
static_cols = [
    'latitude', 'longitude', 'eic_code', 'dso_desc', 'station_type', 'oblast'
]

calendar_cols = [
    'Month', 'Day', 'Hour', 'day_of_week', 'season'
]

def fix_dst(df: pd.DataFrame) -> pd.DataFrame:
    num_cols = df.select_dtypes(include="number").columns.tolist()
    interp_cols = [c for c in num_cols if c not in calendar_cols + ["time_idx"]]

    fixed = []
    dropped = []

    for grp, gdf in df.groupby("eic_code"):
        gdf = gdf.copy().sort_values("datetime")

        # --- DO NOT TOUCH TIMEZONE ---

        # Drop exact duplicates only (keep tz-aware)
        gdf = gdf.drop_duplicates(subset="datetime", keep="first").sort_values("datetime")

        # Create continuous index WITH timezone
        tz = gdf["datetime"].dt.tz
        full_idx = pd.date_range(
            gdf["datetime"].min(),
            gdf["datetime"].max(),
            freq="h",
            tz=tz
        )

        # Check missing timestamps
        missing_mask = ~full_idx.isin(gdf["datetime"])
        if missing_mask.any():
            runs = []
            run_len = 0
            for m in missing_mask:
                if m:
                    run_len += 1
                else:
                    if run_len > 0:
                        runs.append(run_len)
                    run_len = 0
            if run_len > 0:
                runs.append(run_len)

            max_consecutive = max(runs)
            n_missing = missing_mask.sum()

            if max_consecutive > 1:
                print(f"  DROP  {grp}: {n_missing} missing timestamps, "
                      f"max consecutive gap = {max_consecutive}h")
                dropped.append(grp)
                continue
            else:
                print(f"  FILL  {grp}: {n_missing} single-hour gap(s) — interpolating")

        # Reindex (timezone preserved)
        gdf = gdf.set_index("datetime").reindex(full_idx)
        gdf.index.name = "datetime"

        # Fill static cols
        for col in static_cols:
            gdf[col] = gdf[col].ffill().bfill()

        # Interpolate
        gdf[interp_cols] = gdf[interp_cols].interpolate(method="time")

        # Calendar features (tz-aware index works fine)
        gdf["Month"]       = gdf.index.month
        gdf["Day"]         = gdf.index.day
        gdf["Hour"]        = gdf.index.hour
        gdf["day_of_week"] = gdf.index.dayofweek
        gdf["season"]      = (gdf.index.month % 12 // 3 + 1).astype(str)

        gdf = gdf.reset_index()
        fixed.append(gdf)

    print(f"\nSummary: kept {len(fixed)} stations, dropped {len(dropped)} stations")
    if dropped:
        print(f"Dropped: {dropped}")

    result = pd.concat(fixed, ignore_index=True)
    result = result.sort_values(["datetime", "eic_code"]).reset_index(drop=True)

    # time_idx still works with tz-aware timestamps
    base = result.groupby("eic_code")["datetime"].transform(
        lambda s: (s - s.min()).dt.total_seconds() // 3600
    ).astype(int)

    result["time_idx"] = base
    return result

df_gold = fix_dst(df_gold)
df_gold

  FILL  62Z0008583037334: 1 single-hour gap(s) — interpolating
  FILL  62Z0011230718431: 1 single-hour gap(s) — interpolating
  FILL  62Z0096677872985: 1 single-hour gap(s) — interpolating
  FILL  62Z0101426517156: 1 single-hour gap(s) — interpolating
  FILL  62Z013852333354Y: 1 single-hour gap(s) — interpolating
  FILL  62Z0211989286227: 1 single-hour gap(s) — interpolating
  FILL  62Z0257942815672: 1 single-hour gap(s) — interpolating
  FILL  62Z0259886906816: 1 single-hour gap(s) — interpolating
  FILL  62Z0271773349182: 1 single-hour gap(s) — interpolating
  FILL  62Z0285733378448: 3 single-hour gap(s) — interpolating
  FILL  62Z0352290641310: 3 single-hour gap(s) — interpolating
  FILL  62Z0453715929868: 3 single-hour gap(s) — interpolating
  FILL  62Z0494602382356: 3 single-hour gap(s) — interpolating
  FILL  62Z0499856982765: 3 single-hour gap(s) — interpolating
  FILL  62Z052548745986I: 3 single-hour gap(s) — interpolating
  FILL  62Z0611125169123: 3 single-hour gap(s) — interpolating
  FILL  62Z0628247731117: 3 single-hour gap(s) — interpolating
  FILL  62Z0650102958310: 3 single-hour gap(s) — interpolating
  FILL  62Z0760150283041: 3 single-hour gap(s) — interpolating
  FILL  62Z0763594350330: 3 single-hour gap(s) — interpolating
  FILL  62Z0781092622088: 3 single-hour gap(s) — interpolating
  FILL  62Z0832092193888: 3 single-hour gap(s) — interpolating
  FILL  62Z0861889954804: 3 single-hour gap(s) — interpolating
  FILL  62Z0878741618562: 3 single-hour gap(s) — interpolating
  FILL  62Z0961732571457: 3 single-hour gap(s) — interpolating
  FILL  62Z0966299278375: 3 single-hour gap(s) — interpolating
  FILL  62Z0998466306766: 3 single-hour gap(s) — interpolating
  FILL  62Z1008745793703: 3 single-hour gap(s) — interpolating
  FILL  62Z1011664646618: 3 single-hour gap(s) — interpolating
  FILL  62Z1026971387441: 3 single-hour gap(s) — interpolating
  FILL  62Z1037291599086: 3 single-hour gap(s) — interpolating
  FILL  62Z1040856316899: 1 single-hour gap(s) — interpolating
  FILL  62Z1052783389048: 1 single-hour gap(s) — interpolating
  FILL  62Z1067720741039: 1 single-hour gap(s) — interpolating
  FILL  62Z1077202948019: 3 single-hour gap(s) — interpolating
  FILL  62Z1092353551490: 3 single-hour gap(s) — interpolating
  FILL  62Z1108084147506: 1 single-hour gap(s) — interpolating
  FILL  62Z1118549203538: 3 single-hour gap(s) — interpolating
  FILL  62Z1124575209846: 3 single-hour gap(s) — interpolating
  FILL  62Z1175275386589: 1 single-hour gap(s) — interpolating
  FILL  62Z1180469265339: 3 single-hour gap(s) — interpolating
  FILL  62Z1192270413312: 3 single-hour gap(s) — interpolating
  FILL  62Z1209368438999: 3 single-hour gap(s) — interpolating
  FILL  62Z1218299930809: 3 single-hour gap(s) — interpolating
  FILL  62Z131639303888J: 3 single-hour gap(s) — interpolating
  FILL  62Z1325310425194: 3 single-hour gap(s) — interpolating
  FILL  62Z132888029374Z: 3 single-hour gap(s) — interpolating
  FILL  62Z1335377683815: 3 single-hour gap(s) — interpolating
  FILL  62Z1369451614498: 2 single-hour gap(s) — interpolating
  FILL  62Z1393717815036: 3 single-hour gap(s) — interpolating
  FILL  62Z1419007174687: 3 single-hour gap(s) — interpolating
  FILL  62Z1426991213062: 3 single-hour gap(s) — interpolating
  FILL  62Z1471375271708: 3 single-hour gap(s) — interpolating
  FILL  62Z1476408174577: 3 single-hour gap(s) — interpolating
  FILL  62Z1483215110522: 3 single-hour gap(s) — interpolating
  FILL  62Z1515842202934: 3 single-hour gap(s) — interpolating
  FILL  62Z1528625762710: 3 single-hour gap(s) — interpolating
  FILL  62Z1626313673880: 3 single-hour gap(s) — interpolating
  FILL  62Z1657030092515: 3 single-hour gap(s) — interpolating
  FILL  62Z1659898074045: 1 single-hour gap(s) — interpolating
  FILL  62Z1667171467788: 3 single-hour gap(s) — interpolating
  FILL  62Z1699793733727: 3 single-hour gap(s) — interpolating
  FILL  62Z1771663109656: 3 single-hour gap(s) — interpolating
  FILL  62Z1774668832410: 3 single-hour gap(s) — interpolating
  FILL  62Z1776504505608: 3 single-hour gap(s) — interpolating
  FILL  62Z1781749778395: 3 single-hour gap(s) — interpolating
  FILL  62Z1785740293700: 1 single-hour gap(s) — interpolating
  FILL  62Z1785888164071: 3 single-hour gap(s) — interpolating
  FILL  62Z1796820029369: 3 single-hour gap(s) — interpolating
  FILL  62Z1797927643038: 1 single-hour gap(s) — interpolating
  FILL  62Z1811965727106: 3 single-hour gap(s) — interpolating
  FILL  62Z1829125017921: 3 single-hour gap(s) — interpolating
  FILL  62Z1854635779617: 3 single-hour gap(s) — interpolating
  FILL  62Z1908641756932: 3 single-hour gap(s) — interpolating
  FILL  62Z1931450722959: 3 single-hour gap(s) — interpolating
  FILL  62Z1942693584669: 3 single-hour gap(s) — interpolating
  FILL  62Z1971620996431: 3 single-hour gap(s) — interpolating
  FILL  62Z1993541756298: 3 single-hour gap(s) — interpolating
  FILL  62Z2035372013978: 3 single-hour gap(s) — interpolating
  FILL  62Z2063504976595: 3 single-hour gap(s) — interpolating
  FILL  62Z2088310794305: 3 single-hour gap(s) — interpolating
  FILL  62Z2146506845449: 3 single-hour gap(s) — interpolating
  FILL  62Z220653865958K: 3 single-hour gap(s) — interpolating
  FILL  62Z2218971118163: 3 single-hour gap(s) — interpolating
  FILL  62Z2265922863404: 3 single-hour gap(s) — interpolating
  FILL  62Z2295513355879: 3 single-hour gap(s) — interpolating
  FILL  62Z2312293868557: 3 single-hour gap(s) — interpolating
  FILL  62Z2338430234645: 3 single-hour gap(s) — interpolating
  FILL  62Z2395399053131: 3 single-hour gap(s) — interpolating
  FILL  62Z2410378897684: 3 single-hour gap(s) — interpolating
  FILL  62Z2462903940798: 3 single-hour gap(s) — interpolating
  FILL  62Z2496863291167: 3 single-hour gap(s) — interpolating
  FILL  62Z2532379651825: 3 single-hour gap(s) — interpolating
  FILL  62Z2534451404528: 3 single-hour gap(s) — interpolating
  FILL  62Z2548630158379: 3 single-hour gap(s) — interpolating
  FILL  62Z2553437444859: 3 single-hour gap(s) — interpolating
  FILL  62Z2588424624258: 3 single-hour gap(s) — interpolating
  FILL  62Z263077610044S: 3 single-hour gap(s) — interpolating
  FILL  62Z2634468308280: 3 single-hour gap(s) — interpolating
  FILL  62Z2634769525063: 3 single-hour gap(s) — interpolating
  FILL  62Z2636920381647: 3 single-hour gap(s) — interpolating
  FILL  62Z263750576887Y: 3 single-hour gap(s) — interpolating
  FILL  62Z2651182694771: 3 single-hour gap(s) — interpolating
  FILL  62Z2652760199060: 3 single-hour gap(s) — interpolating
  FILL  62Z2655661084314: 3 single-hour gap(s) — interpolating
  FILL  62Z2673921373211: 3 single-hour gap(s) — interpolating
  FILL  62Z2718723694345: 3 single-hour gap(s) — interpolating
  FILL  62Z2749095020078: 1 single-hour gap(s) — interpolating
  FILL  62Z2752425371057: 3 single-hour gap(s) — interpolating
  FILL  62Z2763068988417: 3 single-hour gap(s) — interpolating
  FILL  62Z277440221246K: 3 single-hour gap(s) — interpolating
  FILL  62Z2863396690510: 3 single-hour gap(s) — interpolating
  FILL  62Z2871189104161: 3 single-hour gap(s) — interpolating
  FILL  62Z2923711919630: 3 single-hour gap(s) — interpolating
  FILL  62Z2924124864686: 3 single-hour gap(s) — interpolating
  FILL  62Z2948906740151: 3 single-hour gap(s) — interpolating
  FILL  62Z2986251549800: 2 single-hour gap(s) — interpolating
  FILL  62Z3004068068544: 3 single-hour gap(s) — interpolating
  FILL  62Z3050335819767: 3 single-hour gap(s) — interpolating
  FILL  62Z3064979528589: 1 single-hour gap(s) — interpolating
  FILL  62Z308384437449W: 3 single-hour gap(s) — interpolating
  FILL  62Z3089684577498: 1 single-hour gap(s) — interpolating
  FILL  62Z3123385628010: 3 single-hour gap(s) — interpolating
  FILL  62Z3139295037679: 1 single-hour gap(s) — interpolating
  FILL  62Z3151696887521: 3 single-hour gap(s) — interpolating
  FILL  62Z3251275644497: 3 single-hour gap(s) — interpolating
  FILL  62Z3261331410025: 3 single-hour gap(s) — interpolating
  FILL  62Z3311530591901: 1 single-hour gap(s) — interpolating
  FILL  62Z3319570183213: 1 single-hour gap(s) — interpolating
  FILL  62Z3352742280770: 3 single-hour gap(s) — interpolating
  FILL  62Z3363428137139: 3 single-hour gap(s) — interpolating
  FILL  62Z3386096691495: 3 single-hour gap(s) — interpolating
  FILL  62Z3402828150471: 3 single-hour gap(s) — interpolating
  FILL  62Z3405350712029: 3 single-hour gap(s) — interpolating
  FILL  62Z3418886958455: 3 single-hour gap(s) — interpolating
  FILL  62Z3423083910179: 3 single-hour gap(s) — interpolating
  FILL  62Z3459585554968: 1 single-hour gap(s) — interpolating
  FILL  62Z3470960064884: 3 single-hour gap(s) — interpolating
  FILL  62Z3500556180000: 3 single-hour gap(s) — interpolating
  FILL  62Z3500904013798: 3 single-hour gap(s) — interpolating
  FILL  62Z3522594292484: 3 single-hour gap(s) — interpolating
  FILL  62Z3550947401928: 1 single-hour gap(s) — interpolating
  FILL  62Z3584090129468: 2 single-hour gap(s) — interpolating
  FILL  62Z3599582761965: 3 single-hour gap(s) — interpolating
  FILL  62Z3627036877597: 3 single-hour gap(s) — interpolating
  FILL  62Z3670413006670: 3 single-hour gap(s) — interpolating
  FILL  62Z3714266119413: 1 single-hour gap(s) — interpolating
  FILL  62Z3735193775209: 3 single-hour gap(s) — interpolating
  FILL  62Z3737130651612: 3 single-hour gap(s) — interpolating
  FILL  62Z3760655590536: 3 single-hour gap(s) — interpolating
  FILL  62Z3769305559380: 3 single-hour gap(s) — interpolating
  FILL  62Z3777584435448: 3 single-hour gap(s) — interpolating
  FILL  62Z3782531100736: 3 single-hour gap(s) — interpolating
  FILL  62Z3786741394110: 3 single-hour gap(s) — interpolating
  FILL  62Z3839853638432: 3 single-hour gap(s) — interpolating
  FILL  62Z3896175377334: 3 single-hour gap(s) — interpolating
  FILL  62Z3914826994899: 3 single-hour gap(s) — interpolating
  FILL  62Z3948925189967: 3 single-hour gap(s) — interpolating
  FILL  62Z3958647570133: 3 single-hour gap(s) — interpolating
  FILL  62Z3962336886350: 3 single-hour gap(s) — interpolating
  FILL  62Z3982298183754: 3 single-hour gap(s) — interpolating
  FILL  62Z3982836134374: 3 single-hour gap(s) — interpolating
  FILL  62Z4015550378470: 3 single-hour gap(s) — interpolating
  FILL  62Z4022724546559: 3 single-hour gap(s) — interpolating
  FILL  62Z4026142936382: 3 single-hour gap(s) — interpolating
  FILL  62Z4059172108670: 3 single-hour gap(s) — interpolating
  FILL  62Z4101656497928: 3 single-hour gap(s) — interpolating
  FILL  62Z4106130995736: 3 single-hour gap(s) — interpolating
  FILL  62Z4108523399069: 3 single-hour gap(s) — interpolating
  FILL  62Z4150188688382: 3 single-hour gap(s) — interpolating
  FILL  62Z4166968219279: 3 single-hour gap(s) — interpolating
  FILL  62Z4216533809712: 3 single-hour gap(s) — interpolating
  FILL  62Z4220821460615: 1 single-hour gap(s) — interpolating
  FILL  62Z4242835948103: 3 single-hour gap(s) — interpolating
  FILL  62Z4272248913477: 3 single-hour gap(s) — interpolating
  FILL  62Z4312225157283: 3 single-hour gap(s) — interpolating
  FILL  62Z4312238198106: 3 single-hour gap(s) — interpolating
  FILL  62Z435223622742X: 3 single-hour gap(s) — interpolating
  FILL  62Z4376937874218: 3 single-hour gap(s) — interpolating
  FILL  62Z4393630336378: 3 single-hour gap(s) — interpolating
  FILL  62Z4437758189134: 3 single-hour gap(s) — interpolating
  FILL  62Z4515858754299: 3 single-hour gap(s) — interpolating
  FILL  62Z4534322132001: 3 single-hour gap(s) — interpolating
  FILL  62Z4535568873600: 3 single-hour gap(s) — interpolating
  FILL  62Z4548758318973: 3 single-hour gap(s) — interpolating
  FILL  62Z4603551328872: 3 single-hour gap(s) — interpolating
  FILL  62Z4620750607760: 3 single-hour gap(s) — interpolating
  FILL  62Z4670013981058: 3 single-hour gap(s) — interpolating
  FILL  62Z4695844209784: 3 single-hour gap(s) — interpolating
  FILL  62Z4714370201362: 3 single-hour gap(s) — interpolating
  FILL  62Z4799325639679: 3 single-hour gap(s) — interpolating
  FILL  62Z4867412057712: 3 single-hour gap(s) — interpolating
  FILL  62Z4869256917783: 1 single-hour gap(s) — interpolating
  FILL  62Z4932099022421: 3 single-hour gap(s) — interpolating
  FILL  62Z4935598443531: 3 single-hour gap(s) — interpolating
  FILL  62Z4971310138140: 3 single-hour gap(s) — interpolating
  FILL  62Z4973549241143: 3 single-hour gap(s) — interpolating
  FILL  62Z4988166368088: 1 single-hour gap(s) — interpolating
  FILL  62Z5016551205400: 3 single-hour gap(s) — interpolating
  FILL  62Z5036679942884: 3 single-hour gap(s) — interpolating
  FILL  62Z5038669404578: 3 single-hour gap(s) — interpolating
  FILL  62Z5087432881718: 3 single-hour gap(s) — interpolating
  FILL  62Z510430374778H: 3 single-hour gap(s) — interpolating
  FILL  62Z5156908732276: 3 single-hour gap(s) — interpolating
  FILL  62Z5197867294689: 1 single-hour gap(s) — interpolating
  FILL  62Z5227218120709: 3 single-hour gap(s) — interpolating
  FILL  62Z5276218736734: 3 single-hour gap(s) — interpolating
  FILL  62Z5292138491045: 3 single-hour gap(s) — interpolating
  FILL  62Z5320867133425: 3 single-hour gap(s) — interpolating
  FILL  62Z5360291486920: 3 single-hour gap(s) — interpolating
  FILL  62Z5387901249939: 3 single-hour gap(s) — interpolating
  FILL  62Z5422632680702: 3 single-hour gap(s) — interpolating
  FILL  62Z5423451602138: 1 single-hour gap(s) — interpolating
  FILL  62Z5517692082284: 3 single-hour gap(s) — interpolating
  FILL  62Z5520446881915: 3 single-hour gap(s) — interpolating
  FILL  62Z5523967416230: 3 single-hour gap(s) — interpolating
  FILL  62Z5544769493288: 3 single-hour gap(s) — interpolating
  FILL  62Z5611760007206: 3 single-hour gap(s) — interpolating
  FILL  62Z5641732606491: 3 single-hour gap(s) — interpolating
  FILL  62Z5644220618430: 3 single-hour gap(s) — interpolating
  FILL  62Z568915908644K: 3 single-hour gap(s) — interpolating
  FILL  62Z5700239654314: 3 single-hour gap(s) — interpolating
  FILL  62Z5706564184731: 3 single-hour gap(s) — interpolating
  FILL  62Z5771526107976: 3 single-hour gap(s) — interpolating
  FILL  62Z5773779317696: 3 single-hour gap(s) — interpolating
  FILL  62Z5807715983143: 1 single-hour gap(s) — interpolating
  FILL  62Z5821574095639: 1 single-hour gap(s) — interpolating
  FILL  62Z5838478539480: 2 single-hour gap(s) — interpolating
  FILL  62Z5861103133130: 3 single-hour gap(s) — interpolating
  FILL  62Z588650225523K: 3 single-hour gap(s) — interpolating
  FILL  62Z5917376126498: 3 single-hour gap(s) — interpolating
  FILL  62Z5924116714640: 3 single-hour gap(s) — interpolating
  FILL  62Z5944737391486: 3 single-hour gap(s) — interpolating
  FILL  62Z5996705858655: 3 single-hour gap(s) — interpolating
  FILL  62Z6035944504754: 3 single-hour gap(s) — interpolating
  FILL  62Z6043382821714: 1 single-hour gap(s) — interpolating
  FILL  62Z6070434707477: 3 single-hour gap(s) — interpolating
  FILL  62Z6082894318884: 3 single-hour gap(s) — interpolating
  FILL  62Z6084896400004: 3 single-hour gap(s) — interpolating
  FILL  62Z6091309944129: 3 single-hour gap(s) — interpolating
  FILL  62Z6136241721979: 3 single-hour gap(s) — interpolating
  FILL  62Z6186862204513: 3 single-hour gap(s) — interpolating
  FILL  62Z6235725021728: 3 single-hour gap(s) — interpolating
  FILL  62Z6295419983830: 3 single-hour gap(s) — interpolating
  FILL  62Z6308545383007: 3 single-hour gap(s) — interpolating
  FILL  62Z6337618908569: 3 single-hour gap(s) — interpolating
  FILL  62Z6344783791424: 3 single-hour gap(s) — interpolating
  FILL  62Z6365807395451: 3 single-hour gap(s) — interpolating
  FILL  62Z6413133225959: 3 single-hour gap(s) — interpolating
  FILL  62Z644025308441R: 3 single-hour gap(s) — interpolating
  FILL  62Z6499995405271: 3 single-hour gap(s) — interpolating
  FILL  62Z6526777505245: 3 single-hour gap(s) — interpolating
  FILL  62Z6540712406912: 3 single-hour gap(s) — interpolating
  FILL  62Z6542983815153: 3 single-hour gap(s) — interpolating
  FILL  62Z6571743089872: 3 single-hour gap(s) — interpolating
  FILL  62Z6605113197287: 3 single-hour gap(s) — interpolating
  FILL  62Z661769289704V: 3 single-hour gap(s) — interpolating
  FILL  62Z662465333459B: 3 single-hour gap(s) — interpolating
  FILL  62Z6624735969589: 1 single-hour gap(s) — interpolating
  FILL  62Z6626544596360: 3 single-hour gap(s) — interpolating
  FILL  62Z6634912359403: 1 single-hour gap(s) — interpolating
  FILL  62Z6814717943705: 1 single-hour gap(s) — interpolating
  FILL  62Z6960657066877: 3 single-hour gap(s) — interpolating
  FILL  62Z6961364992272: 3 single-hour gap(s) — interpolating
  FILL  62Z6964799374009: 3 single-hour gap(s) — interpolating
  FILL  62Z6969613150684: 3 single-hour gap(s) — interpolating
  FILL  62Z7027336077892: 3 single-hour gap(s) — interpolating
  FILL  62Z7029546479880: 3 single-hour gap(s) — interpolating
  FILL  62Z7032230667708: 3 single-hour gap(s) — interpolating
  FILL  62Z7036676557692: 3 single-hour gap(s) — interpolating
  FILL  62Z706855223975R: 1 single-hour gap(s) — interpolating
  FILL  62Z7072263538637: 3 single-hour gap(s) — interpolating
  FILL  62Z7081538064702: 1 single-hour gap(s) — interpolating
  FILL  62Z7081576017171: 3 single-hour gap(s) — interpolating
  FILL  62Z7082490910138: 3 single-hour gap(s) — interpolating
  FILL  62Z7083678872650: 3 single-hour gap(s) — interpolating
  FILL  62Z7088382629051: 3 single-hour gap(s) — interpolating
  FILL  62Z7103224563785: 3 single-hour gap(s) — interpolating
  FILL  62Z7109147124378: 3 single-hour gap(s) — interpolating
  FILL  62Z7125526126367: 3 single-hour gap(s) — interpolating
  FILL  62Z713390564870T: 3 single-hour gap(s) — interpolating
  FILL  62Z7156461265052: 3 single-hour gap(s) — interpolating
  FILL  62Z717554526459O: 3 single-hour gap(s) — interpolating
  FILL  62Z7178192222681: 3 single-hour gap(s) — interpolating
  FILL  62Z7219337406431: 3 single-hour gap(s) — interpolating
  FILL  62Z7227986894278: 1 single-hour gap(s) — interpolating
  FILL  62Z7257059210435: 3 single-hour gap(s) — interpolating
  FILL  62Z7258812866213: 3 single-hour gap(s) — interpolating
  FILL  62Z7268415982128: 3 single-hour gap(s) — interpolating
  FILL  62Z7306502515032: 3 single-hour gap(s) — interpolating
  FILL  62Z7401145918482: 3 single-hour gap(s) — interpolating
  FILL  62Z7456298044336: 3 single-hour gap(s) — interpolating
  FILL  62Z7458705390604: 3 single-hour gap(s) — interpolating
  FILL  62Z7497150291839: 3 single-hour gap(s) — interpolating
  FILL  62Z7511957889375: 3 single-hour gap(s) — interpolating
  FILL  62Z7581112729322: 3 single-hour gap(s) — interpolating
  FILL  62Z7591557890876: 3 single-hour gap(s) — interpolating
  FILL  62Z7612261635040: 3 single-hour gap(s) — interpolating
  FILL  62Z7654575712966: 3 single-hour gap(s) — interpolating
  FILL  62Z7682329447008: 3 single-hour gap(s) — interpolating
  FILL  62Z771900708749Y: 1 single-hour gap(s) — interpolating
  FILL  62Z7733696342866: 3 single-hour gap(s) — interpolating
  FILL  62Z7757948039221: 3 single-hour gap(s) — interpolating
  FILL  62Z7764311653541: 3 single-hour gap(s) — interpolating
  FILL  62Z7766151236986: 3 single-hour gap(s) — interpolating
  FILL  62Z7776579634526: 3 single-hour gap(s) — interpolating
  FILL  62Z7841956124522: 3 single-hour gap(s) — interpolating
  FILL  62Z7876545081062: 3 single-hour gap(s) — interpolating
  FILL  62Z7878159195687: 1 single-hour gap(s) — interpolating
  FILL  62Z7932254060039: 3 single-hour gap(s) — interpolating
  FILL  62Z7941626132802: 3 single-hour gap(s) — interpolating
  FILL  62Z7973386804189: 3 single-hour gap(s) — interpolating
  FILL  62Z8036354573038: 3 single-hour gap(s) — interpolating
  FILL  62Z811968840923V: 3 single-hour gap(s) — interpolating
  FILL  62Z8138279652086: 3 single-hour gap(s) — interpolating
  FILL  62Z8150719476557: 3 single-hour gap(s) — interpolating
  FILL  62Z8163712471249: 3 single-hour gap(s) — interpolating

,datetime,eic_code,sum_of_kWh,max_power,max_solar,max_ev,latitude,longitude,dso_desc,station_type,...,snowfall,Month,Day,Hour,day_of_week,season,time_idx,sell_bm_price,buy_bm_price,dam_price
0,2024-01-01 01:00:00+02:00,62Z0008583037334,24.043645,110.0,25.52,0.0,48.442430,22.192190,Ужгород,ОККО-комплекс,...,0.0,1,1,1,0,1,0,0.01,59.85,57.0
1,2024-01-01 01:00:00+02:00,62Z0011230718431,16.720749,52.0,0.00,0.0,51.542106,31.262997,Чернігів,ОККО-міська,...,0.0,1,1,1,0,1,0,0.01,59.85,57.0
2,2024-01-01 01:00:00+02:00,62Z0096677872985,14.889751,35.0,15.00,0.0,48.569660,22.346380,Ужгород,ОККО-трасова,...,0.0,1,1,1,0,1,0,0.01,59.85,57.0
3,2024-01-01 01:00:00+02:00,62Z013852333354Y,44.286251,514.0,50.00,270.0,48.566059,30.230684,Черкаси,ОККО-комплекс,...,0.0,1,1,1,0,1,0,0.01,59.85,57.0
4,2024-01-01 01:00:00+02:00,62Z0211989286227,16.102043,210.0,0.00,0.0,48.279279,26.055273,Чернівці,ОККО-трасова,...,0.0,1,1,1,0,1,0,0.01,59.85,57.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5175456,2025-09-01 03:00:00+03:00,62Z9807667180062,15.496269,85.0,0.00,0.0,48.876403,25.008546,Франківськ,ОККО-міні,...,0.0,9,1,3,0,4,14615,0.01,829.50,790.0
5175457,2025-09-01 03:00:00+03:00,62Z9964019189968,17.007319,80.0,20.00,0.0,49.861099,24.020287,Львів,ОККО-міська,...,0.0,9,1,3,0,4,14615,0.01,829.50,790.0
5175458,2025-09-01 03:00:00+03:00,62Z9967272139607,1.685111,10.0,0.00,0.0,49.514413,34.428297,Полтава,ОККО-міні,...,0.0,9,1,3,0,4,14615,0.01,829.50,790.0
5175459,2025-09-01 03:00:00+03:00,62Z9972124228553,82.799274,320.0,39.15,270.0,50.419477,29.842368,КиївОбл,ОККО-комплекс,...,0.0,9,1,3,0,4,14615,0.01,829.50,790.0
5175460,2025-09-01 03:00:00+03:00,62Z9997819406173,19.783005,80.0,15.00,0.0,49.800007,24.068964,Львів,ОККО-міська,...,0.0,9,1,3,0,4,14615,0.01,829.50,790.0

In [9]:
train_end = pd.Timestamp("2025-07-01", tz=df_gold["datetime"].dt.tz)
val_end = pd.Timestamp("2025-08-01", tz=df_gold["datetime"].dt.tz)

df_gold["data_subset"] = "test"

df_gold.loc[df_gold["datetime"] < train_end, "data_subset"] = "train"

df_gold.loc[
    (df_gold["datetime"] >= train_end) &
    (df_gold["datetime"] < val_end),
    "data_subset"
] = "val"

df_gold

,datetime,eic_code,sum_of_kWh,max_power,max_solar,max_ev,latitude,longitude,dso_desc,station_type,...,Month,Day,Hour,day_of_week,season,time_idx,sell_bm_price,buy_bm_price,dam_price,data_subset
0,2024-01-01 01:00:00+02:00,62Z0008583037334,24.043645,110.0,25.52,0.0,48.442430,22.192190,Ужгород,ОККО-комплекс,...,1,1,1,0,1,0,0.01,59.85,57.0,train
1,2024-01-01 01:00:00+02:00,62Z0011230718431,16.720749,52.0,0.00,0.0,51.542106,31.262997,Чернігів,ОККО-міська,...,1,1,1,0,1,0,0.01,59.85,57.0,train
2,2024-01-01 01:00:00+02:00,62Z0096677872985,14.889751,35.0,15.00,0.0,48.569660,22.346380,Ужгород,ОККО-трасова,...,1,1,1,0,1,0,0.01,59.85,57.0,train
3,2024-01-01 01:00:00+02:00,62Z013852333354Y,44.286251,514.0,50.00,270.0,48.566059,30.230684,Черкаси,ОККО-комплекс,...,1,1,1,0,1,0,0.01,59.85,57.0,train
4,2024-01-01 01:00:00+02:00,62Z0211989286227,16.102043,210.0,0.00,0.0,48.279279,26.055273,Чернівці,ОККО-трасова,...,1,1,1,0,1,0,0.01,59.85,57.0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5175456,2025-09-01 03:00:00+03:00,62Z9807667180062,15.496269,85.0,0.00,0.0,48.876403,25.008546,Франківськ,ОККО-міні,...,9,1,3,0,4,14615,0.01,829.50,790.0,test
5175457,2025-09-01 03:00:00+03:00,62Z9964019189968,17.007319,80.0,20.00,0.0,49.861099,24.020287,Львів,ОККО-міська,...,9,1,3,0,4,14615,0.01,829.50,790.0,test
5175458,2025-09-01 03:00:00+03:00,62Z9967272139607,1.685111,10.0,0.00,0.0,49.514413,34.428297,Полтава,ОККО-міні,...,9,1,3,0,4,14615,0.01,829.50,790.0,test
5175459,2025-09-01 03:00:00+03:00,62Z9972124228553,82.799274,320.0,39.15,270.0,50.419477,29.842368,КиївОбл,ОККО-комплекс,...,9,1,3,0,4,14615,0.01,829.50,790.0,test
5175460,2025-09-01 03:00:00+03:00,62Z9997819406173,19.783005,80.0,15.00,0.0,49.800007,24.068964,Львів,ОККО-міська,...,9,1,3,0,4,14615,0.01,829.50,790.0,test

In [12]:
cols_to_ffill = ['dam_price', 'buy_bm_price', 'sell_bm_price']

df_gold[cols_to_ffill] = df_gold[cols_to_ffill].ffill()

In [13]:
find_missing_timesteps(df_gold)

Empty DataFrame
Columns: [eic_code, missing_count, missing_time_idx]
Index: []

In [14]:
df_gold.to_parquet("data/silver/feature_engineered_built_idx_split.parquet", index=False)
df_gold

,datetime,eic_code,sum_of_kWh,max_power,max_solar,max_ev,latitude,longitude,dso_desc,station_type,...,Month,Day,Hour,day_of_week,season,time_idx,sell_bm_price,buy_bm_price,dam_price,data_subset
0,2024-01-01 01:00:00+02:00,62Z0008583037334,24.043645,110.0,25.52,0.0,48.442430,22.192190,Ужгород,ОККО-комплекс,...,1,1,1,0,1,0,0.01,59.85,57.0,train
1,2024-01-01 01:00:00+02:00,62Z0011230718431,16.720749,52.0,0.00,0.0,51.542106,31.262997,Чернігів,ОККО-міська,...,1,1,1,0,1,0,0.01,59.85,57.0,train
2,2024-01-01 01:00:00+02:00,62Z0096677872985,14.889751,35.0,15.00,0.0,48.569660,22.346380,Ужгород,ОККО-трасова,...,1,1,1,0,1,0,0.01,59.85,57.0,train
3,2024-01-01 01:00:00+02:00,62Z013852333354Y,44.286251,514.0,50.00,270.0,48.566059,30.230684,Черкаси,ОККО-комплекс,...,1,1,1,0,1,0,0.01,59.85,57.0,train
4,2024-01-01 01:00:00+02:00,62Z0211989286227,16.102043,210.0,0.00,0.0,48.279279,26.055273,Чернівці,ОККО-трасова,...,1,1,1,0,1,0,0.01,59.85,57.0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5175456,2025-09-01 03:00:00+03:00,62Z9807667180062,15.496269,85.0,0.00,0.0,48.876403,25.008546,Франківськ,ОККО-міні,...,9,1,3,0,4,14615,0.01,829.50,790.0,test
5175457,2025-09-01 03:00:00+03:00,62Z9964019189968,17.007319,80.0,20.00,0.0,49.861099,24.020287,Львів,ОККО-міська,...,9,1,3,0,4,14615,0.01,829.50,790.0,test
5175458,2025-09-01 03:00:00+03:00,62Z9967272139607,1.685111,10.0,0.00,0.0,49.514413,34.428297,Полтава,ОККО-міні,...,9,1,3,0,4,14615,0.01,829.50,790.0,test
5175459,2025-09-01 03:00:00+03:00,62Z9972124228553,82.799274,320.0,39.15,270.0,50.419477,29.842368,КиївОбл,ОККО-комплекс,...,9,1,3,0,4,14615,0.01,829.50,790.0,test
5175460,2025-09-01 03:00:00+03:00,62Z9997819406173,19.783005,80.0,15.00,0.0,49.800007,24.068964,Львів,ОККО-міська,...,9,1,3,0,4,14615,0.01,829.50,790.0,test

In [15]:
# import pandas as pd
#
# df_gold = pd.read_parquet("data/silver/feature_engineered_built_idx_split.parquet")

In [16]:
# for DL models & transformers

df_gold[df_gold['data_subset'] == "train"].drop(columns=["data_subset"]).to_parquet(
    "data/gold/datetime_time_idx_cat/train.parquet", index=False)
df_gold[df_gold['data_subset'] == "val"].drop(columns=["data_subset"]).to_parquet(
    "data/gold/datetime_time_idx_cat/val.parquet", index=False)
df_gold[df_gold['data_subset'] == "test"].drop(columns=["data_subset"]).to_parquet(
    "data/gold/datetime_time_idx_cat/test.parquet", index=False)

In [17]:
cols_to_ohe = [
    'dso_desc', 'station_type', 'oblast',
    'Month', 'Day', 'Hour', 'day_of_week', 'season'
]

df_gold_ohe = pd.get_dummies(
    df_gold,
    columns=cols_to_ohe,
    drop_first=False
)

df_gold_ohe

,datetime,eic_code,sum_of_kWh,max_power,max_solar,max_ev,latitude,longitude,temperature_2m,relative_humidity_2m,...,day_of_week_1,day_of_week_2,day_of_week_3,day_of_week_4,day_of_week_5,day_of_week_6,season_1,season_2,season_3,season_4
0,2024-01-01 01:00:00+02:00,62Z0008583037334,24.043645,110.0,25.52,0.0,48.442430,22.192190,5.3,81.0,...,False,False,False,False,False,False,True,False,False,False
1,2024-01-01 01:00:00+02:00,62Z0011230718431,16.720749,52.0,0.00,0.0,51.542106,31.262997,1.5,80.0,...,False,False,False,False,False,False,True,False,False,False
2,2024-01-01 01:00:00+02:00,62Z0096677872985,14.889751,35.0,15.00,0.0,48.569660,22.346380,5.2,83.0,...,False,False,False,False,False,False,True,False,False,False
3,2024-01-01 01:00:00+02:00,62Z013852333354Y,44.286251,514.0,50.00,270.0,48.566059,30.230684,-1.9,94.0,...,False,False,False,False,False,False,True,False,False,False
4,2024-01-01 01:00:00+02:00,62Z0211989286227,16.102043,210.0,0.00,0.0,48.279279,26.055273,-0.6,96.0,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5175456,2025-09-01 03:00:00+03:00,62Z9807667180062,15.496269,85.0,0.00,0.0,48.876403,25.008546,17.9,94.0,...,False,False,False,False,False,False,False,False,False,True
5175457,2025-09-01 03:00:00+03:00,62Z9964019189968,17.007319,80.0,20.00,0.0,49.861099,24.020287,18.2,95.0,...,False,False,False,False,False,False,False,False,False,True
5175458,2025-09-01 03:00:00+03:00,62Z9967272139607,1.685111,10.0,0.00,0.0,49.514413,34.428297,19.4,71.0,...,False,False,False,False,False,False,False,False,False,True
5175459,2025-09-01 03:00:00+03:00,62Z9972124228553,82.799274,320.0,39.15,270.0,50.419477,29.842368,19.1,88.0,...,False,False,False,False,False,False,False,False,False,True
5175460,2025-09-01 03:00:00+03:00,62Z9997819406173,19.783005,80.0,15.00,0.0,49.800007,24.068964,18.2,95.0,...,False,False,False,False,False,False,False,False,False,True

In [18]:
# for ML models & SARIMAX

df_gold_ohe[df_gold_ohe['data_subset'] == "train"].drop(columns=["data_subset", "datetime"]).to_parquet(
    "data/gold/time_idx_ohe/train.parquet", index=False)
print("Train:", len(df_gold_ohe[df_gold_ohe['data_subset'] == "train"]))
df_gold_ohe[df_gold_ohe['data_subset'] == "val"].drop(columns=["data_subset", "datetime"]).to_parquet(
    "data/gold/time_idx_ohe/val.parquet", index=False)
print("Val:", len(df_gold_ohe[df_gold_ohe['data_subset'] == "val"]))
df_gold_ohe[df_gold_ohe['data_subset'] == "test"].drop(columns=["data_subset", "datetime"]).to_parquet(
    "data/gold/time_idx_ohe/test.parquet", index=False)
print("Test:", len(df_gold_ohe[df_gold_ohe['data_subset'] == "test"]))

Train: 4586151
Val: 293880
Test: 295430