In [15]:
import pandas as pd
import os
from tqdm.notebook import tqdm

In [16]:
folder = "data/excel_files"

file_paths = [os.path.join(folder, f) for f in os.listdir(folder)]
file_paths

['data/excel_files/2024_9-10.xlsx',
 'data/excel_files/2024_11-12.xlsx',
 'data/excel_files/2024_5-6.xlsx',
 'data/excel_files/2025_5-6.xlsx',
 'data/excel_files/2025_3-4.xlsx',
 'data/excel_files/2024_3-4.xlsx',
 'data/excel_files/2024_1-2.xlsx',
 'data/excel_files/2025_1-2.xlsx',
 'data/excel_files/2024_7-8.xlsx',
 'data/excel_files/2025_7-8.xlsx']

In [17]:
df = pd.DataFrame()
for f in tqdm(file_paths):
    df = pd.concat([df, pd.read_excel(f, sheet_name="DATA", header=5)], ignore_index=True)

df = df[~df['EIC-код'].isin(['Grand Total', 'Загальний підсумок'])].copy()
df

  0%|          | 0/10 [00:00<?, ?it/s]

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год
0,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,1.0,19.264333,2.15221,5.697900
1,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,2.0,16.892233,2.15221,5.697900
2,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,3.0,15.382714,2.15221,5.697900
3,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,4.0,15.598360,2.15221,5.697900
4,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,5.0,14.735777,2.15221,5.697900
...,...,...,...,...,...,...,...,...,...,...
5454717,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,20.0,22.540932,1.76339,5.447321
5454718,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,21.0,24.207382,1.76339,5.447321
5454719,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,22.0,25.211150,1.76339,5.447321
5454720,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,23.0,22.579913,1.76339,5.447321
5454721,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,24.0,19.783005,1.76339,5.447321

In [18]:
static_data_dict = pd.read_excel("data/raw/8month2025.xlsx", sheet_name="Dict")
static_data_dict

,EIC-код,Унікод,АЗС,Тип,Область,Адреса,GPS-координати - Широта,GPS-координати - Довгота,ОСР код,ОСР опис
0,62Z3386096691495,40110200,АЗС_02,ОККО-міська,Львівська,"м. Львів, вул. Замарстинівська, 174",49.871014,24.020029,MGA-00900,Львів
1,62Z5700239654314,40110500,АЗС_05,ОККО-міська,Львівська,"м. Львів, вул. Клепарівська, 30 Б",49.853477,24.014784,MGA-00900,Львів
2,62Z8292498523912,40110700,АЗС_07,ОККО-міська,Львівська,"м. Львів, вул. Володимира Великого, 58",49.812439,23.984974,MGA-00900,Львів
3,62Z6337618908569,40111000,АЗС_10,ОККО-стандарт,Львівська,"м. Львів, вул. Липинського, 54 А",49.864338,24.039696,MGA-00900,Львів
4,62Z1180469265339,40111100,АЗС_11,ОККО-міська,Львівська,"Львів, вул. Джорджа Вашингтона, 12",49.813316,24.077612,MGA-00900,Львів
...,...,...,...,...,...,...,...,...,...,...
424,62Z2673921373211,41261600,АЗС_39,ОККО-трасова,Дніпропетровська,"с/р Новоолександрівська, вздовж АД М-04 Знам'я...",48.430910,34.944208,MGA-02400,Дніпро
425,62Z7841956124522,41062200,АЗС_36,ОККО-стандарт,Дніпропетровська,"м. Дніпро, вул. Каштанова, 4 К",48.501564,35.080823,MGA-02400,Дніпро
426,62Z5821574095639,41261800,АЗС_45,ОККО-міська,Дніпропетровська,"м. Дніпро, Полтавське шосе, 11 К",48.519610,34.989180,MGA-02400,Дніпро
427,62Z1528625762710,41261400,АЗС_46,ОККО-міська,Дніпропетровська,"м. Дніпро, вул. Робоча, 84",48.454806,35.003711,MGA-02400,Дніпро
428,62Z4670013981058,41261300,АЗС_40,ОККО-міська,Дніпропетровська,"м. Дніпро, вул. Панікахи, 31 г",48.399406,35.026860,MGA-02400,Дніпро

In [19]:
eic_code_to_missing_coords = {
    "62Z0602349894257": [48.763904006776954, 28.077456990197557],
    "62Z6035944504754": [49.153510259625534, 23.049801982501872],
    "62Z8888861892130": [48.309249416757545, 25.11895645420284],
    "62Z1209368438999": [49.78531388363913, 24.927028292321978],
    "62Z1771663109656": [49.453445499775405, 23.020911411362146],
    "62Z2532379651825": [49.29362429838761, 23.41030049170128],
    "62Z3261331410025": [49.56421176098104, 23.304357225434188],
    "62Z3627036877597": [48.51882104530565, 28.760435421364264],
    "62Z5422632680702": [50.22822399875523, 24.83726310970472],
    "62Z0763594350330": [49.369735771908296, 23.47527668624802],
    "62Z7029546479880": [49.77948499692157, 24.013408048459073],
    "62Z7072263538637": [49.86242688799433, 24.062926768794956],
    "62Z7766151236986": [50.46762760936502, 24.26123769025777],
    "62Z5064314448909": [48.149046045899055, 23.322957181272095],
    "62Z9342951787758": [49.28552561066835, 23.534192240667057],
    "62Z8521105012164": [48.36054435942602, 29.536275478873062],
    "62Z1142387881356": [49.76402754584019, 31.39902598856454],
    "62Z6624735969589": [48.94419405940688, 24.149295411716132],
    "62Z5956494916290": [49.95178196130912, 25.31699531547816],
    "62Z0717322121288": [48.207039717684104, 23.522199099176],
    "62Z568600499251K": [49.74638889010666, 31.486251700927244],
}

lat_map = {k: v[0] for k, v in eic_code_to_missing_coords.items()}
lon_map = {k: v[1] for k, v in eic_code_to_missing_coords.items()}

static_data_dict["GPS-координати - Широта"] = (
    static_data_dict["GPS-координати - Широта"]
    .fillna(static_data_dict["EIC-код"].map(lat_map))
)

static_data_dict["GPS-координати - Довгота"] = (
    static_data_dict["GPS-координати - Довгота"]
    .fillna(static_data_dict["EIC-код"].map(lon_map))
)
static_data_dict

,EIC-код,Унікод,АЗС,Тип,Область,Адреса,GPS-координати - Широта,GPS-координати - Довгота,ОСР код,ОСР опис
0,62Z3386096691495,40110200,АЗС_02,ОККО-міська,Львівська,"м. Львів, вул. Замарстинівська, 174",49.871014,24.020029,MGA-00900,Львів
1,62Z5700239654314,40110500,АЗС_05,ОККО-міська,Львівська,"м. Львів, вул. Клепарівська, 30 Б",49.853477,24.014784,MGA-00900,Львів
2,62Z8292498523912,40110700,АЗС_07,ОККО-міська,Львівська,"м. Львів, вул. Володимира Великого, 58",49.812439,23.984974,MGA-00900,Львів
3,62Z6337618908569,40111000,АЗС_10,ОККО-стандарт,Львівська,"м. Львів, вул. Липинського, 54 А",49.864338,24.039696,MGA-00900,Львів
4,62Z1180469265339,40111100,АЗС_11,ОККО-міська,Львівська,"Львів, вул. Джорджа Вашингтона, 12",49.813316,24.077612,MGA-00900,Львів
...,...,...,...,...,...,...,...,...,...,...
424,62Z2673921373211,41261600,АЗС_39,ОККО-трасова,Дніпропетровська,"с/р Новоолександрівська, вздовж АД М-04 Знам'я...",48.430910,34.944208,MGA-02400,Дніпро
425,62Z7841956124522,41062200,АЗС_36,ОККО-стандарт,Дніпропетровська,"м. Дніпро, вул. Каштанова, 4 К",48.501564,35.080823,MGA-02400,Дніпро
426,62Z5821574095639,41261800,АЗС_45,ОККО-міська,Дніпропетровська,"м. Дніпро, Полтавське шосе, 11 К",48.519610,34.989180,MGA-02400,Дніпро
427,62Z1528625762710,41261400,АЗС_46,ОККО-міська,Дніпропетровська,"м. Дніпро, вул. Робоча, 84",48.454806,35.003711,MGA-02400,Дніпро
428,62Z4670013981058,41261300,АЗС_40,ОККО-міська,Дніпропетровська,"м. Дніпро, вул. Панікахи, 31 г",48.399406,35.026860,MGA-02400,Дніпро

In [20]:
df = df.merge(static_data_dict, on='EIC-код', how='left', suffixes=('', '_dict'))
df

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,Унікод,АЗС,Тип,Область,Адреса,GPS-координати - Широта,GPS-координати - Довгота,ОСР код,ОСР опис
0,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,1.0,19.264333,2.15221,5.697900,40312900,АЗС_29,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород
1,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,2.0,16.892233,2.15221,5.697900,40312900,АЗС_29,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород
2,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,3.0,15.382714,2.15221,5.697900,40312900,АЗС_29,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород
3,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,4.0,15.598360,2.15221,5.697900,40312900,АЗС_29,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород
4,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,5.0,14.735777,2.15221,5.697900,40312900,АЗС_29,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5454708,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,20.0,22.540932,1.76339,5.447321,40116500,АЗС_65,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів
5454709,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,21.0,24.207382,1.76339,5.447321,40116500,АЗС_65,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів
5454710,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,22.0,25.211150,1.76339,5.447321,40116500,АЗС_65,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів
5454711,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,23.0,22.579913,1.76339,5.447321,40116500,АЗС_65,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів
5454712,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,24.0,19.783005,1.76339,5.447321,40116500,АЗС_65,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів

In [21]:
df['Дата'] = pd.to_datetime(df['Дата'], errors='coerce')
df['Дата'] = df['Дата'] + pd.to_timedelta(df['Hour'].fillna(0), unit='h')
df

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,Унікод,АЗС,Тип,Область,Адреса,GPS-координати - Широта,GPS-координати - Довгота,ОСР код,ОСР опис
0,62Z0008583037334,Б,2024-09-01 01:00:00,2024.0,9.0,1.0,1.0,19.264333,2.15221,5.697900,40312900,АЗС_29,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород
1,62Z0008583037334,Б,2024-09-01 02:00:00,2024.0,9.0,1.0,2.0,16.892233,2.15221,5.697900,40312900,АЗС_29,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород
2,62Z0008583037334,Б,2024-09-01 03:00:00,2024.0,9.0,1.0,3.0,15.382714,2.15221,5.697900,40312900,АЗС_29,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород
3,62Z0008583037334,Б,2024-09-01 04:00:00,2024.0,9.0,1.0,4.0,15.598360,2.15221,5.697900,40312900,АЗС_29,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород
4,62Z0008583037334,Б,2024-09-01 05:00:00,2024.0,9.0,1.0,5.0,14.735777,2.15221,5.697900,40312900,АЗС_29,ОККО-комплекс,Закарпатська,"Ужгородський р-н, с. Соломоново, автодорога Ки...",48.442430,22.192190,MGA-00700,Ужгород
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5454708,62Z9997819406173,Б,2025-08-31 20:00:00,2025.0,8.0,31.0,20.0,22.540932,1.76339,5.447321,40116500,АЗС_65,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів
5454709,62Z9997819406173,Б,2025-08-31 21:00:00,2025.0,8.0,31.0,21.0,24.207382,1.76339,5.447321,40116500,АЗС_65,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів
5454710,62Z9997819406173,Б,2025-08-31 22:00:00,2025.0,8.0,31.0,22.0,25.211150,1.76339,5.447321,40116500,АЗС_65,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів
5454711,62Z9997819406173,Б,2025-08-31 23:00:00,2025.0,8.0,31.0,23.0,22.579913,1.76339,5.447321,40116500,АЗС_65,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів
5454712,62Z9997819406173,Б,2025-09-01 00:00:00,2025.0,8.0,31.0,24.0,19.783005,1.76339,5.447321,40116500,АЗС_65,ОККО-міська,Львівська,"м. Львів, вул. Зелена, 283",49.800007,24.068964,MGA-00900,Львів

In [29]:
electricity_prices_df = pd.read_excel('data/raw/8month2025.xlsx', sheet_name="ЦіниРДН", header=2)[['Year', 'Month', 'Day', 'Година', 'Average of Ціна, грн без ПДВ/кВт']]

electricity_prices_df = electricity_prices_df[electricity_prices_df['Year'] != 'Grand Total'].copy()

electricity_prices_df['Дата'] = pd.to_datetime(
    electricity_prices_df[['Year', 'Month', 'Day']].assign(hour=electricity_prices_df['Година'])
)
electricity_prices_df

,Year,Month,Day,Година,"Average of Ціна, грн без ПДВ/кВт",Дата
0,2024,1.0,1.0,1.0,0.05700,2024-01-01 01:00:00
1,2024,1.0,1.0,2.0,0.05700,2024-01-01 02:00:00
2,2024,1.0,1.0,3.0,0.05555,2024-01-01 03:00:00
3,2024,1.0,1.0,4.0,0.03800,2024-01-01 04:00:00
4,2024,1.0,1.0,5.0,0.03200,2024-01-01 05:00:00
...,...,...,...,...,...,...
15594,2025,10.0,11.0,20.0,14.95073,2025-10-11 20:00:00
15595,2025,10.0,11.0,21.0,14.95057,2025-10-11 21:00:00
15596,2025,10.0,11.0,22.0,14.94907,2025-10-11 22:00:00
15597,2025,10.0,11.0,23.0,14.94767,2025-10-11 23:00:00
15598,2025,10.0,11.0,24.0,6.89051,2025-10-12 00:00:00

In [ ]:
df = df.merge(
    electricity_prices_df[['Дата', 'Average of Ціна, грн без ПДВ/кВт']],
    on='Дата',
    how='left'
)

# replace values
df['Average of Ціна ЕЕ грн. без ПДВ/кВт*год'] = df['Average of Ціна, грн без ПДВ/кВт']

# optionally drop helper column
df = df.drop(columns=['Average of Ціна, грн без ПДВ/кВт'])

In [32]:
distr_prices_df = pd.read_excel('data/raw/8month2025.xlsx', sheet_name="Dist_price")
distr_prices_df

    Year  Month  Distr_price
0   2024      1        0.529
1   2024      2        0.529
2   2024      3        0.529
3   2024      4        0.529
4   2024      5        0.529
5   2024      6        0.529
6   2024      7        0.529
7   2024      8        0.529
8   2024      9        0.529
9   2024     10        0.529
10  2024     11        0.529
11  2024     12        0.529
12  2025      1        0.686
13  2025      2        0.686
14  2025      3        0.686
15  2025      4        0.686
16  2025      5        0.686
17  2025      6        0.686
18  2025      7        0.686
19  2025      8        0.686
20  2025      9        0.686
21  2025     10        0.686
22  2025     11        0.686
23  2025     12        0.686

In [ ]:
# df = df.merge(
#     distr_prices_df[['Year', 'Month', 'Distr_price']],
#     on=['Year', 'Month'],
#     how='left'
# )
#
# # replace values
# df['Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год'] = df['Distr_price']
#
# # optionally drop helper column
# df = df.drop(columns=['Distr_price'])

In [22]:
cols_to_leave = ['EIC-код', 'Група', 'Дата', 'Sum of кВт',
                 'Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год', 'Average of Ціна ЕЕ грн. без ПДВ/кВт*год',
                 'Область', 'GPS-координати - Широта', 'GPS-координати - Довгота', 'ОСР опис', 'Адреса']

rename_cols = {
    'Дата': 'datetime',
    'EIC-код': 'EIC-код_cat',
    'Група': 'Група_cat',
    'Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год': 'Ціна розподілу ЕЕ',
    'Average of Ціна ЕЕ грн. без ПДВ/кВт*год': 'Ціна ЕЕ',
    'Область': 'Область_cat',
    'GPS-координати - Широта': 'Широта',
    'GPS-координати - Довгота': 'Довгота',
    'ОСР опис': 'ОСР опис_cat'
}

weather_cols_to_create = ['temperature_2m',
       'apparent_temperature', 'dew_point_2m', 'relative_humidity_2m',
       'precipitation', 'rain', 'snowfall', 'cloud_cover', 'cloud_cover_low',
       'cloud_cover_mid', 'cloud_cover_high', 'surface_pressure',
       'wind_speed_10m', 'wind_direction_10m', 'wind_gusts_10m',
       'shortwave_radiation', 'diffuse_radiation', 'direct_normal_irradiance']

In [23]:
df = df[cols_to_leave].copy()
df = df.rename(columns=rename_cols)
df

,EIC-код_cat,Група_cat,datetime,Sum of кВт,Ціна розподілу ЕЕ,Ціна ЕЕ,Область_cat,Широта,Довгота,ОСР опис_cat,Адреса
0,62Z0008583037334,Б,2024-09-01 01:00:00,19.264333,2.15221,5.697900,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки..."
1,62Z0008583037334,Б,2024-09-01 02:00:00,16.892233,2.15221,5.697900,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки..."
2,62Z0008583037334,Б,2024-09-01 03:00:00,15.382714,2.15221,5.697900,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки..."
3,62Z0008583037334,Б,2024-09-01 04:00:00,15.598360,2.15221,5.697900,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки..."
4,62Z0008583037334,Б,2024-09-01 05:00:00,14.735777,2.15221,5.697900,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки..."
...,...,...,...,...,...,...,...,...,...,...,...
5454708,62Z9997819406173,Б,2025-08-31 20:00:00,22.540932,1.76339,5.447321,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283"
5454709,62Z9997819406173,Б,2025-08-31 21:00:00,24.207382,1.76339,5.447321,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283"
5454710,62Z9997819406173,Б,2025-08-31 22:00:00,25.211150,1.76339,5.447321,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283"
5454711,62Z9997819406173,Б,2025-08-31 23:00:00,22.579913,1.76339,5.447321,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283"
5454712,62Z9997819406173,Б,2025-09-01 00:00:00,19.783005,1.76339,5.447321,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283"

In [24]:
mask = (
    (df["EIC-код_cat"] == "62Z8521105012164") &
    (df["datetime"] <= "2024-06-01 00:00:00")
)

df = df.loc[~mask]

In [25]:
mask = df["EIC-код_cat"] == "62Z8937841078757"

df.loc[mask, "Ціна розподілу ЕЕ"] = 2.31163

In [26]:
print(f"Stations before dropping: {len(df['EIC-код_cat'].unique())}, rows: {len(df)}")

global_end = df["datetime"].max()

# station-level stats
g = df.groupby("EIC-код_cat")["datetime"]

station_stats = pd.DataFrame({
    "start": g.min(),
    "end": g.max(),
    "n_hours": g.count()
})

# rule 1: must have data near dataset end (within 7 days tolerance)
station_stats["reaches_end"] = station_stats["end"] >= (global_end - pd.Timedelta(days=7))

# rule 2: must have at least 3 months of REAL observations
station_stats[">=3_months_data"] = station_stats["n_hours"] >= 90 * 24

# final filter
valid_stations = station_stats[
    station_stats["reaches_end"] &
    station_stats[">=3_months_data"]
].index

df = df[df["EIC-код_cat"].isin(valid_stations)].copy()

print(f"Stations after dropping: {len(df['EIC-код_cat'].unique())}, rows: {len(df)}")

Stations before dropping: 411, rows: 5451066
Stations after dropping: 395, rows: 5341641

In [27]:
df

,EIC-код_cat,Група_cat,datetime,Sum of кВт,Ціна розподілу ЕЕ,Ціна ЕЕ,Область_cat,Широта,Довгота,ОСР опис_cat,Адреса
0,62Z0008583037334,Б,2024-09-01 01:00:00,19.264333,2.15221,5.697900,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки..."
1,62Z0008583037334,Б,2024-09-01 02:00:00,16.892233,2.15221,5.697900,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки..."
2,62Z0008583037334,Б,2024-09-01 03:00:00,15.382714,2.15221,5.697900,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки..."
3,62Z0008583037334,Б,2024-09-01 04:00:00,15.598360,2.15221,5.697900,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки..."
4,62Z0008583037334,Б,2024-09-01 05:00:00,14.735777,2.15221,5.697900,Закарпатська,48.442430,22.192190,Ужгород,"Ужгородський р-н, с. Соломоново, автодорога Ки..."
...,...,...,...,...,...,...,...,...,...,...,...
5454708,62Z9997819406173,Б,2025-08-31 20:00:00,22.540932,1.76339,5.447321,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283"
5454709,62Z9997819406173,Б,2025-08-31 21:00:00,24.207382,1.76339,5.447321,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283"
5454710,62Z9997819406173,Б,2025-08-31 22:00:00,25.211150,1.76339,5.447321,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283"
5454711,62Z9997819406173,Б,2025-08-31 23:00:00,22.579913,1.76339,5.447321,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283"
5454712,62Z9997819406173,Б,2025-09-01 00:00:00,19.783005,1.76339,5.447321,Львівська,49.800007,24.068964,Львів,"м. Львів, вул. Зелена, 283"

In [28]:
aaa

NameError: name 'aaa' is not defined

In [10]:
path = "data/bronze/no_weather.parquet"
weather_path = "data/bronze/with_weather.parquet"
checkpoint_path = "data/bronze/checkpoint.parquet"

In [11]:
df.to_parquet(path, index=False)
df

,EIC-код_cat,Група_cat,datetime,Sum of кВт,Ціна розподілу ЕЕ,Ціна ЕЕ,Область_cat,Широта,Довгота,ОСР опис_cat
0,62Z0101426517156,А,2025-01-01 01:00:00,14.3,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси
1,62Z0101426517156,А,2025-01-01 02:00:00,13.8,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси
2,62Z0101426517156,А,2025-01-01 03:00:00,13.9,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси
3,62Z0101426517156,А,2025-01-01 04:00:00,12.9,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси
4,62Z0101426517156,А,2025-01-01 05:00:00,12.2,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси

In [12]:
from weather import smart_requests

df_with_weather = smart_requests(
    path_in=path,
    path_out=weather_path,
    checkpoint_path=checkpoint_path,
    eic_code_name='EIC-код_cat',
    lat_col='Широта',
    lon_col='Довгота',
)
df_with_weather

Gas stations with weather: 0
Gas stations with no weather: 1

Gas stations:   0%|          | 0/1 [00:00<?, ?it/s]

,EIC-код_cat,Група_cat,datetime,Sum of кВт,Ціна розподілу ЕЕ,Ціна ЕЕ,Область_cat,Широта,Довгота,ОСР опис_cat,...,cloud_cover_high,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,direct_normal_irradiance,diffuse_radiation,precipitation,rain,snowfall
0,62Z0101426517156,А,2025-01-01 01:00:00+02:00,14.3,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси,...,0.0,14.6,257.0,24.1,0.0,0.0,0.0,0.0,0.0,0.0
1,62Z0101426517156,А,2025-01-01 02:00:00+02:00,13.8,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси,...,0.0,14.0,262.0,24.5,0.0,0.0,0.0,0.0,0.0,0.0
2,62Z0101426517156,А,2025-01-01 03:00:00+02:00,13.9,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси,...,0.0,13.3,267.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0
3,62Z0101426517156,А,2025-01-01 04:00:00+02:00,12.9,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси,...,0.0,14.2,268.0,25.6,0.0,0.0,0.0,0.0,0.0,0.0
4,62Z0101426517156,А,2025-01-01 05:00:00+02:00,12.2,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси,...,0.0,12.1,266.0,23.4,0.0,0.0,0.0,0.0,0.0,0.0