In [55]:
import pandas as pd
import os
from tqdm.notebook import tqdm

In [56]:
folder = "data/excel_files"

file_paths = [os.path.join(folder, f) for f in os.listdir(folder)]
file_paths

['data/excel_files/2024_9-10.xlsx',
 'data/excel_files/2024_11-12.xlsx',
 'data/excel_files/2024_5-6.xlsx',
 'data/excel_files/2025_5-6.xlsx',
 'data/excel_files/2025_3-4.xlsx',
 'data/excel_files/2024_3-4.xlsx',
 'data/excel_files/2024_1-2.xlsx',
 'data/excel_files/2025_1-2.xlsx',
 'data/excel_files/2024_7-8.xlsx',
 'data/excel_files/2025_7-8.xlsx']

In [57]:
df = pd.DataFrame()
for f in tqdm(file_paths):
    df = pd.concat([df, pd.read_excel(f, sheet_name="DATA", header=5)], ignore_index=True)

df = df[df['EIC-код'] != 'Grand Total'].copy()
df

  0%|          | 0/10 [00:00<?, ?it/s]

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год
0,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,1.0,1.926433e+01,2.152210,5.697900
1,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,2.0,1.689223e+01,2.152210,5.697900
2,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,3.0,1.538271e+01,2.152210,5.697900
3,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,4.0,1.559836e+01,2.152210,5.697900
4,62Z0008583037334,Б,2024-09-01,2024.0,9.0,1.0,5.0,1.473578e+01,2.152210,5.697900
...,...,...,...,...,...,...,...,...,...,...
5454718,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,21.0,2.420738e+01,1.763390,5.447321
5454719,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,22.0,2.521115e+01,1.763390,5.447321
5454720,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,23.0,2.257991e+01,1.763390,5.447321
5454721,62Z9997819406173,Б,2025-08-31,2025.0,8.0,31.0,24.0,1.978301e+01,1.763390,5.447321
5454722,Загальний підсумок,NaN,NaT,NaN,NaN,NaN,NaN,1.115051e+07,1.868452,5.444159

In [67]:
static_data_dict = pd.read_excel("data/raw/8month2025.xlsx", sheet_name="Dict")
static_data_dict

,EIC-код,Унікод,АЗС,Тип,Область,Адреса,GPS-координати - Широта,GPS-координати - Довгота,ОСР код,ОСР опис
0,62Z3386096691495,40110200,АЗС_02,ОККО-міська,Львівська,"м. Львів, вул. Замарстинівська, 174",49.871014,24.020029,MGA-00900,Львів
1,62Z5700239654314,40110500,АЗС_05,ОККО-міська,Львівська,"м. Львів, вул. Клепарівська, 30 Б",49.853477,24.014784,MGA-00900,Львів
2,62Z8292498523912,40110700,АЗС_07,ОККО-міська,Львівська,"м. Львів, вул. Володимира Великого, 58",49.812439,23.984974,MGA-00900,Львів
3,62Z6337618908569,40111000,АЗС_10,ОККО-стандарт,Львівська,"м. Львів, вул. Липинського, 54 А",49.864338,24.039696,MGA-00900,Львів
4,62Z1180469265339,40111100,АЗС_11,ОККО-міська,Львівська,"Львів, вул. Джорджа Вашингтона, 12",49.813316,24.077612,MGA-00900,Львів
...,...,...,...,...,...,...,...,...,...,...
424,62Z2673921373211,41261600,АЗС_39,ОККО-трасова,Дніпропетровська,"с/р Новоолександрівська, вздовж АД М-04 Знам'я...",48.430910,34.944208,MGA-02400,Дніпро
425,62Z7841956124522,41062200,АЗС_36,ОККО-стандарт,Дніпропетровська,"м. Дніпро, вул. Каштанова, 4 К",48.501564,35.080823,MGA-02400,Дніпро
426,62Z5821574095639,41261800,АЗС_45,ОККО-міська,Дніпропетровська,"м. Дніпро, Полтавське шосе, 11 К",48.519610,34.989180,MGA-02400,Дніпро
427,62Z1528625762710,41261400,АЗС_46,ОККО-міська,Дніпропетровська,"м. Дніпро, вул. Робоча, 84",48.454806,35.003711,MGA-02400,Дніпро
428,62Z4670013981058,41261300,АЗС_40,ОККО-міська,Дніпропетровська,"м. Дніпро, вул. Панікахи, 31 г",48.399406,35.026860,MGA-02400,Дніпро

In [68]:
static_data_dict['ОСР опис'].value_counts()

ОСР опис
Львів            70
Ужгород          31
КиївОбл          30
Франківськ       29
Вінниця          29
Київ             26
Дніпро           25
Харків           24
Одеса            19
Рівне            17
Хмельницький     15
Тернопіль        12
Волинь           11
Кропивницький    10
Херсон           10
Полтава           9
Черкаси           9
Чернівці          9
Житомир           8
Запоріжжя         8
УЗ                8
Донецьк           7
Чернігів          5
Суми              3
Миколаїв          2
НафтогазНР        1
НафтогазНЯ        1
ЦЕК               1
Name: count, dtype: int64

In [5]:
df = df.merge(static_data_dict, on='EIC-код', how='left', suffixes=('', '_dict'))
df

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,Унікод,АЗС,Тип,Область,Адреса,GPS-координати - Широта,GPS-координати - Довгота,ОСР код,ОСР опис
0,62Z0101426517156,А,2025-01-01,2025.0,1.0,1.0,1.0,14.3,1.92964,6.03446,40214400,АЗС_44,ОККО-комплекс,Черкаська,"Уманський р-н, с/р Ладижинська, автодорога Киї...",48.567394,30.232208,MGA-01900,Черкаси
1,62Z0101426517156,А,2025-01-01,2025.0,1.0,1.0,2.0,13.8,1.92964,6.03446,40214400,АЗС_44,ОККО-комплекс,Черкаська,"Уманський р-н, с/р Ладижинська, автодорога Киї...",48.567394,30.232208,MGA-01900,Черкаси
2,62Z0101426517156,А,2025-01-01,2025.0,1.0,1.0,3.0,13.9,1.92964,6.03446,40214400,АЗС_44,ОККО-комплекс,Черкаська,"Уманський р-н, с/р Ладижинська, автодорога Киї...",48.567394,30.232208,MGA-01900,Черкаси
3,62Z0101426517156,А,2025-01-01,2025.0,1.0,1.0,4.0,12.9,1.92964,6.03446,40214400,АЗС_44,ОККО-комплекс,Черкаська,"Уманський р-н, с/р Ладижинська, автодорога Киї...",48.567394,30.232208,MGA-01900,Черкаси
4,62Z0101426517156,А,2025-01-01,2025.0,1.0,1.0,5.0,12.2,1.92964,6.03446,40214400,АЗС_44,ОККО-комплекс,Черкаська,"Уманський р-н, с/р Ладижинська, автодорога Киї...",48.567394,30.232208,MGA-01900,Черкаси

In [6]:
df['Дата'] = pd.to_datetime(df['Дата'], errors='coerce')
df['Дата'] = df['Дата'] + pd.to_timedelta(df['Hour'].fillna(0), unit='h')
df

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,Унікод,АЗС,Тип,Область,Адреса,GPS-координати - Широта,GPS-координати - Довгота,ОСР код,ОСР опис
0,62Z0101426517156,А,2025-01-01 01:00:00,2025.0,1.0,1.0,1.0,14.3,1.92964,6.03446,40214400,АЗС_44,ОККО-комплекс,Черкаська,"Уманський р-н, с/р Ладижинська, автодорога Киї...",48.567394,30.232208,MGA-01900,Черкаси
1,62Z0101426517156,А,2025-01-01 02:00:00,2025.0,1.0,1.0,2.0,13.8,1.92964,6.03446,40214400,АЗС_44,ОККО-комплекс,Черкаська,"Уманський р-н, с/р Ладижинська, автодорога Киї...",48.567394,30.232208,MGA-01900,Черкаси
2,62Z0101426517156,А,2025-01-01 03:00:00,2025.0,1.0,1.0,3.0,13.9,1.92964,6.03446,40214400,АЗС_44,ОККО-комплекс,Черкаська,"Уманський р-н, с/р Ладижинська, автодорога Киї...",48.567394,30.232208,MGA-01900,Черкаси
3,62Z0101426517156,А,2025-01-01 04:00:00,2025.0,1.0,1.0,4.0,12.9,1.92964,6.03446,40214400,АЗС_44,ОККО-комплекс,Черкаська,"Уманський р-н, с/р Ладижинська, автодорога Киї...",48.567394,30.232208,MGA-01900,Черкаси
4,62Z0101426517156,А,2025-01-01 05:00:00,2025.0,1.0,1.0,5.0,12.2,1.92964,6.03446,40214400,АЗС_44,ОККО-комплекс,Черкаська,"Уманський р-н, с/р Ладижинська, автодорога Киї...",48.567394,30.232208,MGA-01900,Черкаси

In [8]:
cols_to_leave = ['EIC-код', 'Група', 'Дата', 'Sum of кВт',
                 'Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год', 'Average of Ціна ЕЕ грн. без ПДВ/кВт*год',
                 'Область', 'GPS-координати - Широта', 'GPS-координати - Довгота', 'ОСР опис']

rename_cols = {
    'Дата': 'datetime',
    'EIC-код': 'EIC-код_cat',
    'Група': 'Група_cat',
    'Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год': 'Ціна розподілу ЕЕ',
    'Average of Ціна ЕЕ грн. без ПДВ/кВт*год': 'Ціна ЕЕ',
    'Область': 'Область_cat',
    'GPS-координати - Широта': 'Широта',
    'GPS-координати - Довгота': 'Довгота',
    'ОСР опис': 'ОСР опис_cat'
}

weather_cols_to_create = ['temperature_2m',
       'apparent_temperature', 'dew_point_2m', 'relative_humidity_2m',
       'precipitation', 'rain', 'snowfall', 'cloud_cover', 'cloud_cover_low',
       'cloud_cover_mid', 'cloud_cover_high', 'surface_pressure',
       'wind_speed_10m', 'wind_direction_10m', 'wind_gusts_10m',
       'shortwave_radiation', 'diffuse_radiation', 'direct_normal_irradiance']

In [9]:
df = df[cols_to_leave].copy()
df = df.rename(columns=rename_cols)
df

,EIC-код_cat,Група_cat,datetime,Sum of кВт,Ціна розподілу ЕЕ,Ціна ЕЕ,Область_cat,Широта,Довгота,ОСР опис_cat
0,62Z0101426517156,А,2025-01-01 01:00:00,14.3,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси
1,62Z0101426517156,А,2025-01-01 02:00:00,13.8,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси
2,62Z0101426517156,А,2025-01-01 03:00:00,13.9,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси
3,62Z0101426517156,А,2025-01-01 04:00:00,12.9,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси
4,62Z0101426517156,А,2025-01-01 05:00:00,12.2,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси

In [10]:
path = "data/bronze/no_weather.parquet"
weather_path = "data/bronze/with_weather.parquet"
checkpoint_path = "data/bronze/checkpoint.parquet"

In [11]:
df.to_parquet(path, index=False)
df

,EIC-код_cat,Група_cat,datetime,Sum of кВт,Ціна розподілу ЕЕ,Ціна ЕЕ,Область_cat,Широта,Довгота,ОСР опис_cat
0,62Z0101426517156,А,2025-01-01 01:00:00,14.3,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси
1,62Z0101426517156,А,2025-01-01 02:00:00,13.8,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси
2,62Z0101426517156,А,2025-01-01 03:00:00,13.9,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси
3,62Z0101426517156,А,2025-01-01 04:00:00,12.9,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси
4,62Z0101426517156,А,2025-01-01 05:00:00,12.2,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси

In [12]:
from weather import smart_requests

df_with_weather = smart_requests(
    path_in=path,
    path_out=weather_path,
    checkpoint_path=checkpoint_path,
    eic_code_name='EIC-код_cat',
    lat_col='Широта',
    lon_col='Довгота',
)
df_with_weather

Gas stations with weather: 0
Gas stations with no weather: 1

Gas stations:   0%|          | 0/1 [00:00<?, ?it/s]

,EIC-код_cat,Група_cat,datetime,Sum of кВт,Ціна розподілу ЕЕ,Ціна ЕЕ,Область_cat,Широта,Довгота,ОСР опис_cat,...,cloud_cover_high,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,direct_normal_irradiance,diffuse_radiation,precipitation,rain,snowfall
0,62Z0101426517156,А,2025-01-01 01:00:00+02:00,14.3,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси,...,0.0,14.6,257.0,24.1,0.0,0.0,0.0,0.0,0.0,0.0
1,62Z0101426517156,А,2025-01-01 02:00:00+02:00,13.8,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси,...,0.0,14.0,262.0,24.5,0.0,0.0,0.0,0.0,0.0,0.0
2,62Z0101426517156,А,2025-01-01 03:00:00+02:00,13.9,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси,...,0.0,13.3,267.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0
3,62Z0101426517156,А,2025-01-01 04:00:00+02:00,12.9,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси,...,0.0,14.2,268.0,25.6,0.0,0.0,0.0,0.0,0.0,0.0
4,62Z0101426517156,А,2025-01-01 05:00:00+02:00,12.2,1.92964,6.03446,Черкаська,48.567394,30.232208,Черкаси,...,0.0,12.1,266.0,23.4,0.0,0.0,0.0,0.0,0.0,0.0