In [1]:
import pandas as pd
import numpy as np

from more_features import cols_to_drop

In [3]:
df = pd.read_parquet("../data/silver/dataset_with_weather_time_features.parquet")
df.reset_index(inplace=True)
df.drop(columns=["index"], inplace=True)
df

,EIC-код,Група,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,АЗС,...,cloud_cover_high,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,diffuse_radiation,direct_normal_irradiance,day_of_week,season_number
0,62Z0211989286227,0,2024,12,1,1,16.497020,1.46219,6.136750,АЗС_23,...,0.0,1016.9,4.2,95.0,8.6,0.0,0.0,0.0,6,1
1,62Z0211989286227,0,2024,12,1,2,14.932647,1.46219,6.136750,АЗС_23,...,0.0,1016.6,4.5,85.0,9.0,0.0,0.0,0.0,6,1
2,62Z0211989286227,0,2024,12,1,3,14.363785,1.46219,6.136750,АЗС_23,...,0.0,1016.4,6.0,100.0,11.9,0.0,0.0,0.0,6,1
3,62Z0211989286227,0,2024,12,1,4,13.794922,1.46219,6.136750,АЗС_23,...,0.0,1016.0,6.4,101.0,12.6,0.0,0.0,0.0,6,1
4,62Z0211989286227,0,2024,12,1,5,13.937137,1.46219,6.136750,АЗС_23,...,0.0,1015.7,6.4,117.0,11.9,0.0,0.0,0.0,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5454708,62Z5692449931680,0,2024,1,31,20,12.619683,1.63103,3.662765,АЗС_12,...,0.0,998.5,14.7,242.0,24.5,0.0,0.0,0.0,2,1
5454709,62Z5692449931680,0,2024,1,31,21,12.331140,1.63103,3.662765,АЗС_12,...,0.0,998.4,13.8,250.0,24.1,0.0,0.0,0.0,2,1
5454710,62Z5692449931680,0,2024,1,31,22,11.568950,1.63103,3.662765,АЗС_12,...,0.0,997.9,14.3,252.0,23.8,0.0,0.0,0.0,2,1
5454711,62Z5692449931680,0,2024,1,31,23,10.534550,1.63103,3.662765,АЗС_12,...,0.0,997.3,13.9,253.0,23.8,0.0,0.0,0.0,2,1
5454712,62Z5692449931680,0,2024,1,31,24,9.532815,1.63103,3.662765,АЗС_12,...,0.0,996.9,13.6,253.0,23.0,0.0,0.0,0.0,3,1

In [4]:
df["Money_spent"] = (
    df["Sum of кВт"]
    * (
        df["Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год"]
        + df["Average of Ціна ЕЕ грн. без ПДВ/кВт*год"]
    )
)

df.drop(columns=["Sum of кВт"], inplace=True)
df

,EIC-код,Група,Year,Month,Day,Hour,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,АЗС,Тип,...,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,diffuse_radiation,direct_normal_irradiance,day_of_week,season_number,Money_spent
0,62Z0211989286227,0,2024,12,1,1,1.46219,6.136750,АЗС_23,ОККО-трасова,...,1016.9,4.2,95.0,8.6,0.0,0.0,0.0,6,1,125.359866
1,62Z0211989286227,0,2024,12,1,2,1.46219,6.136750,АЗС_23,ОККО-трасова,...,1016.6,4.5,85.0,9.0,0.0,0.0,0.0,6,1,113.472293
2,62Z0211989286227,0,2024,12,1,3,1.46219,6.136750,АЗС_23,ОККО-трасова,...,1016.4,6.0,100.0,11.9,0.0,0.0,0.0,6,1,109.149539
3,62Z0211989286227,0,2024,12,1,4,1.46219,6.136750,АЗС_23,ОККО-трасова,...,1016.0,6.4,101.0,12.6,0.0,0.0,0.0,6,1,104.826785
4,62Z0211989286227,0,2024,12,1,5,1.46219,6.136750,АЗС_23,ОККО-трасова,...,1015.7,6.4,117.0,11.9,0.0,0.0,0.0,6,1,105.907473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5454708,62Z5692449931680,0,2024,1,31,20,1.63103,3.662765,АЗС_12,ОККО-міні,...,998.5,14.7,242.0,24.5,0.0,0.0,0.0,2,1,66.806020
5454709,62Z5692449931680,0,2024,1,31,21,1.63103,3.662765,АЗС_12,ОККО-міні,...,998.4,13.8,250.0,24.1,0.0,0.0,0.0,2,1,65.278531
5454710,62Z5692449931680,0,2024,1,31,22,1.63103,3.662765,АЗС_12,ОККО-міні,...,997.9,14.3,252.0,23.8,0.0,0.0,0.0,2,1,61.243655
5454711,62Z5692449931680,0,2024,1,31,23,1.63103,3.662765,АЗС_12,ОККО-міні,...,997.3,13.9,253.0,23.8,0.0,0.0,0.0,2,1,55.767752
5454712,62Z5692449931680,0,2024,1,31,24,1.63103,3.662765,АЗС_12,ОККО-міні,...,996.9,13.6,253.0,23.0,0.0,0.0,0.0,3,1,50.464772

In [5]:
df.to_parquet("data/silver_money_calc/full_dataset.parquet", index=False)

In [33]:
df = pd.read_parquet("../data/silver/dataset_with_weather_time_features.parquet")

In [34]:
df

,EIC-код,Група,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,АЗС,...,cloud_cover_high,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,diffuse_radiation,direct_normal_irradiance,day_of_week,season_number
4464,62Z0211989286227,0,2024,12,1,1,16.497020,1.46219,6.136750,АЗС_23,...,0.0,1016.9,4.2,95.0,8.6,0.0,0.0,0.0,6,1
4465,62Z0211989286227,0,2024,12,1,2,14.932647,1.46219,6.136750,АЗС_23,...,0.0,1016.6,4.5,85.0,9.0,0.0,0.0,0.0,6,1
4466,62Z0211989286227,0,2024,12,1,3,14.363785,1.46219,6.136750,АЗС_23,...,0.0,1016.4,6.0,100.0,11.9,0.0,0.0,0.0,6,1
4467,62Z0211989286227,0,2024,12,1,4,13.794922,1.46219,6.136750,АЗС_23,...,0.0,1016.0,6.4,101.0,12.6,0.0,0.0,0.0,6,1
4468,62Z0211989286227,0,2024,12,1,5,13.937137,1.46219,6.136750,АЗС_23,...,0.0,1015.7,6.4,117.0,11.9,0.0,0.0,0.0,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4362,62Z5692449931680,0,2024,1,31,20,12.619683,1.63103,3.662765,АЗС_12,...,0.0,998.5,14.7,242.0,24.5,0.0,0.0,0.0,2,1
4363,62Z5692449931680,0,2024,1,31,21,12.331140,1.63103,3.662765,АЗС_12,...,0.0,998.4,13.8,250.0,24.1,0.0,0.0,0.0,2,1
4364,62Z5692449931680,0,2024,1,31,22,11.568950,1.63103,3.662765,АЗС_12,...,0.0,997.9,14.3,252.0,23.8,0.0,0.0,0.0,2,1
4365,62Z5692449931680,0,2024,1,31,23,10.534550,1.63103,3.662765,АЗС_12,...,0.0,997.3,13.9,253.0,23.8,0.0,0.0,0.0,2,1
4366,62Z5692449931680,0,2024,1,31,24,9.532815,1.63103,3.662765,АЗС_12,...,0.0,996.9,13.6,253.0,23.0,0.0,0.0,0.0,3,1

In [35]:
# categorical columns
categorical_cols = ['Група', 'АЗС', 'Тип', 'Область', 'ОСР код', 'ОСР опис', 'EIC-код']

cols_to_drop = ['Year', 'Month', 'Day', 'Hour', 'day_of_week', 'season_number', 'Адреса']

df = df.drop(columns=cols_to_drop)

# 1. Add _cat suffix to categorical columns
df = df.rename(columns={col: f"{col}_cat" for col in categorical_cols})

# 2. Rename price columns
df = df.rename(columns={
    'Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год': 'Ціна розподілу ЕЕ',
    'Average of Ціна ЕЕ грн. без ПДВ/кВт*год': 'Ціна ЕЕ',
    'GPS-координати - Широта': 'Широта',
    'GPS-координати - Довгота': 'Довгота'
})
df

,EIC-код_cat,Група_cat,Sum of кВт,Ціна розподілу ЕЕ,Ціна ЕЕ,АЗС_cat,Тип_cat,Область_cat,Широта,Довгота,...,cloud_cover_low,cloud_cover_mid,cloud_cover_high,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,diffuse_radiation,direct_normal_irradiance
4464,62Z0211989286227,0,16.497020,1.46219,6.136750,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,...,100.0,0.0,0.0,1016.9,4.2,95.0,8.6,0.0,0.0,0.0
4465,62Z0211989286227,0,14.932647,1.46219,6.136750,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,...,100.0,0.0,0.0,1016.6,4.5,85.0,9.0,0.0,0.0,0.0
4466,62Z0211989286227,0,14.363785,1.46219,6.136750,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,...,100.0,0.0,0.0,1016.4,6.0,100.0,11.9,0.0,0.0,0.0
4467,62Z0211989286227,0,13.794922,1.46219,6.136750,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,...,100.0,0.0,0.0,1016.0,6.4,101.0,12.6,0.0,0.0,0.0
4468,62Z0211989286227,0,13.937137,1.46219,6.136750,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,...,62.0,0.0,0.0,1015.7,6.4,117.0,11.9,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4362,62Z5692449931680,0,12.619683,1.63103,3.662765,АЗС_12,ОККО-міні,Львівська,50.094982,23.434658,...,100.0,54.0,0.0,998.5,14.7,242.0,24.5,0.0,0.0,0.0
4363,62Z5692449931680,0,12.331140,1.63103,3.662765,АЗС_12,ОККО-міні,Львівська,50.094982,23.434658,...,100.0,30.0,0.0,998.4,13.8,250.0,24.1,0.0,0.0,0.0
4364,62Z5692449931680,0,11.568950,1.63103,3.662765,АЗС_12,ОККО-міні,Львівська,50.094982,23.434658,...,100.0,100.0,0.0,997.9,14.3,252.0,23.8,0.0,0.0,0.0
4365,62Z5692449931680,0,10.534550,1.63103,3.662765,АЗС_12,ОККО-міні,Львівська,50.094982,23.434658,...,100.0,100.0,0.0,997.3,13.9,253.0,23.8,0.0,0.0,0.0
4366,62Z5692449931680,0,9.532815,1.63103,3.662765,АЗС_12,ОККО-міні,Львівська,50.094982,23.434658,...,100.0,77.0,0.0,996.9,13.6,253.0,23.0,0.0,0.0,0.0

In [38]:
df['Sum of кВт'] = df['Sum of кВт'].clip(lower=0)

df["Money_spent"] = (
    df["Sum of кВт"]
    * (
        df['Ціна розподілу ЕЕ']
        + df['Ціна ЕЕ']
      )
)
df

,EIC-код_cat,Група_cat,Sum of кВт,Ціна розподілу ЕЕ,Ціна ЕЕ,АЗС_cat,Тип_cat,Область_cat,Широта,Довгота,...,cloud_cover_mid,cloud_cover_high,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,diffuse_radiation,direct_normal_irradiance,Money_spent
4464,62Z0211989286227,0,16.497020,1.46219,6.136750,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,...,0.0,0.0,1016.9,4.2,95.0,8.6,0.0,0.0,0.0,125.359866
4465,62Z0211989286227,0,14.932647,1.46219,6.136750,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,...,0.0,0.0,1016.6,4.5,85.0,9.0,0.0,0.0,0.0,113.472293
4466,62Z0211989286227,0,14.363785,1.46219,6.136750,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,...,0.0,0.0,1016.4,6.0,100.0,11.9,0.0,0.0,0.0,109.149539
4467,62Z0211989286227,0,13.794922,1.46219,6.136750,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,...,0.0,0.0,1016.0,6.4,101.0,12.6,0.0,0.0,0.0,104.826785
4468,62Z0211989286227,0,13.937137,1.46219,6.136750,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,...,0.0,0.0,1015.7,6.4,117.0,11.9,0.0,0.0,0.0,105.907473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4362,62Z5692449931680,0,12.619683,1.63103,3.662765,АЗС_12,ОККО-міні,Львівська,50.094982,23.434658,...,54.0,0.0,998.5,14.7,242.0,24.5,0.0,0.0,0.0,66.806020
4363,62Z5692449931680,0,12.331140,1.63103,3.662765,АЗС_12,ОККО-міні,Львівська,50.094982,23.434658,...,30.0,0.0,998.4,13.8,250.0,24.1,0.0,0.0,0.0,65.278531
4364,62Z5692449931680,0,11.568950,1.63103,3.662765,АЗС_12,ОККО-міні,Львівська,50.094982,23.434658,...,100.0,0.0,997.9,14.3,252.0,23.8,0.0,0.0,0.0,61.243655
4365,62Z5692449931680,0,10.534550,1.63103,3.662765,АЗС_12,ОККО-міні,Львівська,50.094982,23.434658,...,100.0,0.0,997.3,13.9,253.0,23.8,0.0,0.0,0.0,55.767752
4366,62Z5692449931680,0,9.532815,1.63103,3.662765,АЗС_12,ОККО-міні,Львівська,50.094982,23.434658,...,77.0,0.0,996.9,13.6,253.0,23.0,0.0,0.0,0.0,50.464772

In [39]:
test = df[df['datetime'] > '2025-07-31']
test.to_parquet("data/silver_money_calc/test.parquet", index=False)

val = df[(df['datetime'] > '2025-06-30') & (df['datetime'] < '2025-08-01')]
val.to_parquet("data/silver_money_calc/val.parquet", index=False)

train = df[df['datetime'] < '2025-07-01']
train.to_parquet("data/silver_money_calc/train.parquet", index=False)

In [26]:
df.columns

Index(['EIC-код_cat', 'Група_cat', 'Ціна розподілу ЕЕ', 'Ціна ЕЕ', 'АЗС_cat',
       'Тип_cat', 'Область_cat', 'Широта', 'Довгота', 'ОСР код_cat',
       'ОСР опис_cat', 'datetime', 'temperature_2m', 'apparent_temperature',
       'dew_point_2m', 'relative_humidity_2m', 'precipitation', 'rain',
       'snowfall', 'cloud_cover', 'cloud_cover_low', 'cloud_cover_mid',
       'cloud_cover_high', 'surface_pressure', 'wind_speed_10m',
       'wind_direction_10m', 'wind_gusts_10m', 'shortwave_radiation',
       'diffuse_radiation', 'direct_normal_irradiance', 'Money_spent'],
      dtype='object')