In [1]:
import pandas as pd

df = pd.read_parquet("../data/silver_money_calc/test.parquet")
df

,EIC-код_cat,Група_cat,Sum of кВт,Ціна розподілу ЕЕ,Ціна ЕЕ,АЗС_cat,Тип_cat,Область_cat,Широта,Довгота,...,cloud_cover_mid,cloud_cover_high,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,diffuse_radiation,direct_normal_irradiance,Money_spent
0,62Z0211989286227,1,21.000000,1.67615,5.441006,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,...,1.0,0.0,996.0,10.1,290.0,18.7,0.0,0.0,0.0,149.460267
1,62Z0211989286227,1,17.000000,1.67615,5.441006,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,...,0.0,0.0,995.7,9.8,288.0,18.7,0.0,0.0,0.0,120.991645
2,62Z0211989286227,1,17.000000,1.67615,5.441006,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,...,0.0,0.0,996.0,11.1,290.0,22.0,0.0,0.0,0.0,120.991645
3,62Z0211989286227,1,16.000000,1.67615,5.441006,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,...,0.0,0.0,995.8,10.6,294.0,20.5,0.0,0.0,0.0,113.874489
4,62Z0211989286227,1,16.000000,1.67615,5.441006,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,...,0.0,0.0,996.0,10.1,294.0,19.8,0.0,0.0,0.0,113.874489
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304147,62Z9512175266041,0,26.379837,0.81260,5.447321,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,...,0.0,0.0,995.3,9.9,27.0,18.7,0.0,0.0,0.0,165.135700
304148,62Z9512175266041,0,27.803749,0.81260,5.447321,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,...,0.0,0.0,994.8,10.5,27.0,20.2,0.0,0.0,0.0,174.049275
304149,62Z9512175266041,0,27.429035,0.81260,5.447321,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,...,4.0,0.0,994.6,10.0,36.0,20.5,0.0,0.0,0.0,171.703597
304150,62Z9512175266041,0,25.068339,0.81260,5.447321,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,...,1.0,0.0,994.5,9.5,37.0,19.1,0.0,0.0,0.0,156.925829
304151,62Z9512175266041,0,21.321203,0.81260,5.447321,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,...,0.0,0.0,994.2,9.0,35.0,18.0,0.0,0.0,0.0,133.469053

In [2]:
time_col = 'datetime'

FUTURE_REALS = [
    'temperature_2m', 'apparent_temperature',
       'dew_point_2m', 'relative_humidity_2m', 'precipitation', 'rain',
       'snowfall', 'cloud_cover', 'cloud_cover_low', 'cloud_cover_mid',
       'cloud_cover_high', 'surface_pressure', 'wind_speed_10m',
       'wind_direction_10m', 'wind_gusts_10m', 'shortwave_radiation',
       'diffuse_radiation', 'direct_normal_irradiance'
]

# ── Numerical real-valued covariates NOT known at forecast time ─────────────────
PAST_REALS = ['Ціна розподілу ЕЕ', 'Ціна ЕЕ', "Money_spent"]   # add any columns that are only available historically

# ── Static numerical covariates (one value per station, time-invariant) ─────────
STATIC_REALS = [
    'Широта', 'Довгота',
]

# ── Categorical time-varying known covariates ───────────────────────────────────
# Calendar categoricals — always known in the future
TIME_VARYING_KNOWN_CATS = [
    "Year_cat", "Month_cat", "Day_cat", "Hour_cat", "day_of_week_cat", "season_cat"
]  # are not present in the dataset, created by a func later

# ── Static categoricals ─────────────────────────────────────────────────────────
STATIC_CATS = ['EIC-код_cat', 'Група_cat', 'АЗС_cat', 'Тип_cat', 'Область_cat', 'ОСР код_cat', 'ОСР опис_cat']

In [3]:
df.drop(columns=FUTURE_REALS + PAST_REALS + ['Sum of кВт'], inplace=True)
df

,EIC-код_cat,Група_cat,АЗС_cat,Тип_cat,Область_cat,Широта,Довгота,ОСР код_cat,ОСР опис_cat,datetime
0,62Z0211989286227,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці,2025-07-31 01:00:00+03:00
1,62Z0211989286227,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці,2025-07-31 02:00:00+03:00
2,62Z0211989286227,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці,2025-07-31 03:00:00+03:00
3,62Z0211989286227,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці,2025-07-31 04:00:00+03:00
4,62Z0211989286227,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці,2025-07-31 05:00:00+03:00
...,...,...,...,...,...,...,...,...,...,...
304147,62Z9512175266041,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ,2025-08-31 20:00:00+03:00
304148,62Z9512175266041,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ,2025-08-31 21:00:00+03:00
304149,62Z9512175266041,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ,2025-08-31 22:00:00+03:00
304150,62Z9512175266041,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ,2025-08-31 23:00:00+03:00
304151,62Z9512175266041,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ,2025-09-01 00:00:00+03:00

In [4]:
def generate_datetime_per_eic(
    df: pd.DataFrame,
    start: str,
    end: str,
    freq: str = "H"
) -> pd.DataFrame:
    """
    For each unique 'EIC-код_cat', generate a full datetime range
    and keep all other column values constant per EIC.

    Parameters:
    - df: input dataframe (must contain 'EIC-код_cat')
    - start: start datetime
    - end: end datetime
    - freq: frequency (default 'H')

    Returns:
    - Expanded DataFrame with datetime + original columns
    """

    # Ensure unique rows per EIC (important!)
    base = df.drop_duplicates(subset=['EIC-код_cat'])

    # Create datetime range
    date_range = pd.date_range(start=start, end=end, freq=freq)

    # Create cartesian product
    expanded = pd.MultiIndex.from_product(
        [base['EIC-код_cat'], date_range],
        names=['EIC-код_cat', 'datetime']
    ).to_frame(index=False)

    # Merge back original columns
    result = expanded.merge(base.drop(columns=['datetime']), on='EIC-код_cat', how='left')

    return result

future_df = generate_datetime_per_eic(df, start = '2025-09-01 00:00:00+0300', end = '2026-04-01 00:00:00+0300')
future_df

C:\Users\Lev\AppData\Local\Temp\ipykernel_29152\1962186952.py:25: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  date_range = pd.date_range(start=start, end=end, freq=freq)

,EIC-код_cat,datetime,Група_cat,АЗС_cat,Тип_cat,Область_cat,Широта,Довгота,ОСР код_cat,ОСР опис_cat
0,62Z0211989286227,2025-09-01 00:00:00+03:00,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці
1,62Z0211989286227,2025-09-01 01:00:00+03:00,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці
2,62Z0211989286227,2025-09-01 02:00:00+03:00,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці
3,62Z0211989286227,2025-09-01 03:00:00+03:00,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці
4,62Z0211989286227,2025-09-01 04:00:00+03:00,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці
...,...,...,...,...,...,...,...,...,...,...
2025417,62Z9512175266041,2026-03-31 20:00:00+03:00,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ
2025418,62Z9512175266041,2026-03-31 21:00:00+03:00,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ
2025419,62Z9512175266041,2026-03-31 22:00:00+03:00,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ
2025420,62Z9512175266041,2026-03-31 23:00:00+03:00,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ
2025421,62Z9512175266041,2026-04-01 00:00:00+03:00,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ

In [5]:
future_df.to_parquet("data/no_y_col/no_weather.parquet", index=False)

In [6]:
WEATHER_FILE  = "../data/no_y_col/with_weather.parquet"
TARGET_FILE   = "../data/no_y_col/no_weather.parquet"
OUTPUT_FILE   = "../data/no_y_col/with_weather_v2.parquet"

# Column names used as the join key — adjust if your files use different names
LAT_COL      = "Широта"
LON_COL      = "Довгота"
DT_COL       = "datetime"

WEATHER_COLS = FUTURE_REALS

# ── Load ──────────────────────────────────────────────────────────────────────

print(f"Loading {WEATHER_FILE} ...")
weather_df = pd.read_parquet(WEATHER_FILE)
weather_df = weather_df.rename(columns={
    'GPS-координати - Широта': 'Широта',
    'GPS-координати - Довгота': 'Довгота'
})

print(f"Loading {TARGET_FILE} ...")
target_df  = pd.read_parquet(TARGET_FILE)

# ── Validate columns exist ────────────────────────────────────────────────────

key_cols = [LAT_COL, LON_COL, DT_COL]

for col in key_cols:
    assert col in weather_df.columns, f"Key column '{col}' missing from {WEATHER_FILE}"
    assert col in target_df.columns,  f"Key column '{col}' missing from {TARGET_FILE}"

missing_weather_cols = [c for c in WEATHER_COLS if c not in weather_df.columns]
if missing_weather_cols:
    raise ValueError(f"Weather columns missing from {WEATHER_FILE}: {missing_weather_cols}")

# ── Align datetime types (both files must match for the join to work) ─────────

for df, name in [(weather_df, WEATHER_FILE), (target_df, TARGET_FILE)]:
    if not pd.api.types.is_datetime64_any_dtype(df[DT_COL]):
        print(f"  Converting '{DT_COL}' in {name} to datetime ...")
        df[DT_COL] = pd.to_datetime(df[DT_COL])

# ── Build a lookup table from the weather file ────────────────────────────────
# Keep only the columns we need to avoid bloating memory on large files.

lookup = (
    weather_df[key_cols + WEATHER_COLS]
    .drop_duplicates(subset=key_cols)   # one row per (lat, lon, dt) combo
    .set_index(key_cols)
)

print(f"Lookup table: {len(lookup):,} unique (lat, lon, datetime) combos")

# ── Drop pre-existing weather columns from target (avoid _x/_y suffixes) ──────

cols_to_drop = [c for c in WEATHER_COLS if c in target_df.columns]
if cols_to_drop:
    print(f"  Dropping existing columns from target: {cols_to_drop}")
    target_df = target_df.drop(columns=cols_to_drop)

# ── Merge ─────────────────────────────────────────────────────────────────────

print("Merging weather columns ...")
result_df = target_df.merge(
    lookup.reset_index(),
    on=key_cols,
    how="left",       # keep all rows from target; unmatched rows → NaN
    validate="m:1",   # each target row matches at most one lookup row
)

# ── Report coverage ───────────────────────────────────────────────────────────

n_total   = len(result_df)
n_matched = result_df["temperature_2m"].notna().sum()
n_missing = n_total - n_matched

print(f"\nRows total  : {n_total:,}")
print(f"Rows matched: {n_matched:,}")
if n_missing:
    print(f"Rows with no weather match (NaN): {n_missing:,}")
    print("  → Check that lat/lon precision and datetime format are identical in both files.")

Loading data/no_y_col/with_weather.parquet ...
Loading data/no_y_col/no_weather.parquet ...
Lookup table: 1,655,093 unique (lat, lon, datetime) combos
Merging weather columns ...

Rows total  : 2,025,422
Rows matched: 1,737,288
Rows with no weather match (NaN): 288,134
  → Check that lat/lon precision and datetime format are identical in both files.

In [7]:
result_df

,EIC-код_cat,datetime,Група_cat,АЗС_cat,Тип_cat,Область_cat,Широта,Довгота,ОСР код_cat,ОСР опис_cat,...,cloud_cover_low,cloud_cover_mid,cloud_cover_high,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,diffuse_radiation,direct_normal_irradiance
0,62Z0211989286227,2025-09-01 00:00:00+03:00,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,62Z0211989286227,2025-09-01 01:00:00+03:00,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,62Z0211989286227,2025-09-01 02:00:00+03:00,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,62Z0211989286227,2025-09-01 03:00:00+03:00,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,62Z0211989286227,2025-09-01 04:00:00+03:00,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025417,62Z9512175266041,2026-03-31 20:00:00+03:00,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ,...,12.0,70.0,97.0,993.0,9.2,344.0,18.0,5.0,5.0,0.0
2025418,62Z9512175266041,2026-03-31 21:00:00+03:00,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ,...,27.0,47.0,88.0,993.6,7.2,3.0,18.4,0.0,0.0,0.0
2025419,62Z9512175266041,2026-03-31 22:00:00+03:00,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ,...,2.0,43.0,97.0,994.1,10.1,354.0,19.1,0.0,0.0,0.0
2025420,62Z9512175266041,2026-03-31 23:00:00+03:00,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ,...,17.0,35.0,100.0,994.2,8.2,352.0,19.8,0.0,0.0,0.0
2025421,62Z9512175266041,2026-04-01 00:00:00+03:00,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ,...,16.0,66.0,66.0,994.7,5.7,325.0,15.8,0.0,0.0,0.0

In [8]:
# ── Save ──────────────────────────────────────────────────────────────────────

print(f"\nSaving → {OUTPUT_FILE}")
result_df.to_parquet(OUTPUT_FILE, index=False)
print("Done.")

Saving → data/no_y_col/with_weather_v2.parquet
Done.

In [5]:
from data_pipeline.weather import *

smart_requests(path_in="../data/no_y_col/with_weather_v2.parquet", path_out="../data/no_y_col/with_weather_v2.parquet", checkpoint_path="../data/no_y_col/weather_checkpoint.parquet", eic_code_name ='EIC-код_cat', lat_col ="Широта", lon_col ="Довгота", sleep_time=1)

Gas stations with weather: 398
Gas stations with no weather: 390

Gas stations:   0%|          | 0/390 [00:00<?, ?it/s]

,EIC-код_cat,datetime,Група_cat,АЗС_cat,Тип_cat,Область_cat,Широта,Довгота,ОСР код_cat,ОСР опис_cat,...,cloud_cover_low,cloud_cover_mid,cloud_cover_high,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,diffuse_radiation,direct_normal_irradiance
720,62Z0211989286227,2025-10-01 00:00:00+03:00,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці,...,100.0,100.0,85.0,1004.2,10.8,18.0,19.4,0.0,0.0,0.0
721,62Z0211989286227,2025-10-01 01:00:00+03:00,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці,...,100.0,100.0,57.0,1004.2,13.6,44.0,23.8,0.0,0.0,0.0
722,62Z0211989286227,2025-10-01 02:00:00+03:00,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці,...,100.0,100.0,6.0,1004.2,13.0,56.0,25.6,0.0,0.0,0.0
723,62Z0211989286227,2025-10-01 03:00:00+03:00,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці,...,100.0,100.0,5.0,1004.4,17.3,68.0,23.4,0.0,0.0,0.0
724,62Z0211989286227,2025-10-01 04:00:00+03:00,1,АЗС_23,ОККО-трасова,Чернівецька,48.279279,26.055273,MGA-00300,Чернівці,...,100.0,100.0,28.0,1004.4,14.2,64.0,31.3,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,62Z9512175266041,2025-09-30 23:00:00+03:00,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ,...,0.0,96.0,100.0,1014.8,13.3,77.0,31.7,0.0,0.0,0.0
720,62Z9512175266041,2025-10-01 00:00:00+03:00,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ,...,0.0,100.0,100.0,1014.5,12.2,74.0,29.2,0.0,0.0,0.0
721,62Z9512175266041,2025-10-01 01:00:00+03:00,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ,...,0.0,100.0,100.0,1014.2,11.3,70.0,26.6,0.0,0.0,0.0
722,62Z9512175266041,2025-10-01 02:00:00+03:00,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ,...,0.0,100.0,98.0,1014.0,10.7,67.0,24.8,0.0,0.0,0.0
723,62Z9512175266041,2025-10-26 03:00:00+02:00,0,АЗС_60,ОККО-стандарт,м. Київ,50.403745,30.684027,MGA-03000,Київ,...,0.0,0.0,72.0,994.8,9.8,211.0,20.9,0.0,0.0,0.0