In [28]:
import pandas as pd

In [29]:
df = pd.read_parquet('../data/raw/data_no_weather.parquet')
df

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,...,surface_pressure,pressure_msl,visibility,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,direct_radiation,diffuse_radiation,direct_normal_irradiance
0,62Z0008583037334,Б,2024-12-01,2024,12,1,1,20.716983,2.15221,6.136750,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,62Z0008583037334,Б,2024-12-01,2024,12,1,2,19.365875,2.15221,6.136750,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,62Z0008583037334,Б,2024-12-01,2024,12,1,3,18.529475,2.15221,6.136750,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,62Z0008583037334,Б,2024-12-01,2024,12,1,4,18.207783,2.15221,6.136750,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,62Z0008583037334,Б,2024-12-01,2024,12,1,5,17.886091,2.15221,6.136750,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4612447,62Z9997819406173,Б,2024-01-31,2024,1,31,20,25.794128,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612448,62Z9997819406173,Б,2024-01-31,2024,1,31,21,25.204357,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612449,62Z9997819406173,Б,2024-01-31,2024,1,31,22,23.646472,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612450,62Z9997819406173,Б,2024-01-31,2024,1,31,23,21.532199,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612451,62Z9997819406173,Б,2024-01-31,2024,1,31,24,19.484693,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df_weathered = pd.read_parquet('../data/raw/data_with_weather.parquet')

In [26]:
df_weathered = pd.concat([df[~df['temperature_2m'].isna()], df_weathered]).copy()
df_weathered.to_parquet('data/raw/data_with_weather.parquet')
df_weathered

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,...,surface_pressure,pressure_msl,visibility,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,direct_radiation,diffuse_radiation,direct_normal_irradiance
4464,62Z0211989286227,Б,2024-12-01,2024,12,1,1,16.497020,1.46219,6.136750,...,1016.9,1036.5,None,4.2,95.0,8.6,0.0,0.0,0.0,0.0
4465,62Z0211989286227,Б,2024-12-01,2024,12,1,2,14.932647,1.46219,6.136750,...,1016.6,1036.2,None,4.5,85.0,9.0,0.0,0.0,0.0,0.0
4466,62Z0211989286227,Б,2024-12-01,2024,12,1,3,14.363785,1.46219,6.136750,...,1016.4,1035.9,None,6.0,100.0,11.9,0.0,0.0,0.0,0.0
4467,62Z0211989286227,Б,2024-12-01,2024,12,1,4,13.794922,1.46219,6.136750,...,1016.0,1035.5,None,6.4,101.0,12.6,0.0,0.0,0.0,0.0
4468,62Z0211989286227,Б,2024-12-01,2024,12,1,5,13.937137,1.46219,6.136750,...,1015.7,1035.2,None,6.4,117.0,11.9,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439828,62Z9342951787758,Б,2024-01-31,2024,1,31,20,2.455705,1.63103,3.662765,...,1012.4,1012.4,None,16.4,195.0,22.7,79.0,25.0,54.0,133.3
5439829,62Z9342951787758,Б,2024-01-31,2024,1,31,21,2.399557,1.63103,3.662765,...,1013.2,1013.2,None,15.4,191.0,23.4,2.0,0.0,2.0,0.0
5439830,62Z9342951787758,Б,2024-01-31,2024,1,31,22,2.251240,1.63103,3.662765,...,1014.0,1014.0,None,11.6,187.0,21.2,0.0,0.0,0.0,0.0
5439831,62Z9342951787758,Б,2024-01-31,2024,1,31,23,2.049953,1.63103,3.662765,...,1014.4,1014.4,None,9.8,186.0,16.9,0.0,0.0,0.0,0.0
5439832,62Z9342951787758,Б,2024-01-31,2024,1,31,24,1.855022,1.63103,3.662765,...,1014.9,1014.9,None,10.1,176.0,14.8,0.0,0.0,0.0,0.0

In [27]:
df[df['temperature_2m'].isna()].to_parquet('data/raw/data_no_weather.parquet')
df[df['temperature_2m'].isna()]

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,...,surface_pressure,pressure_msl,visibility,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,direct_radiation,diffuse_radiation,direct_normal_irradiance
0,62Z0008583037334,Б,2024-12-01,2024,12,1,1,20.716983,2.15221,6.136750,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,62Z0008583037334,Б,2024-12-01,2024,12,1,2,19.365875,2.15221,6.136750,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,62Z0008583037334,Б,2024-12-01,2024,12,1,3,18.529475,2.15221,6.136750,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,62Z0008583037334,Б,2024-12-01,2024,12,1,4,18.207783,2.15221,6.136750,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,62Z0008583037334,Б,2024-12-01,2024,12,1,5,17.886091,2.15221,6.136750,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4612447,62Z9997819406173,Б,2024-01-31,2024,1,31,20,25.794128,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612448,62Z9997819406173,Б,2024-01-31,2024,1,31,21,25.204357,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612449,62Z9997819406173,Б,2024-01-31,2024,1,31,22,23.646472,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612450,62Z9997819406173,Б,2024-01-31,2024,1,31,23,21.532199,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612451,62Z9997819406173,Б,2024-01-31,2024,1,31,24,19.484693,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
pd.concat([df_weathered, df]).to_parquet('../data/raw/full_concated_copy.parquet')
pd.concat([df_weathered, df])

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,...,surface_pressure,pressure_msl,visibility,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,direct_radiation,diffuse_radiation,direct_normal_irradiance
4464,62Z0211989286227,Б,2024-12-01,2024,12,1,1,16.497020,1.46219,6.136750,...,1016.9,1036.5,None,4.2,95.0,8.6,0.0,0.0,0.0,0.0
4465,62Z0211989286227,Б,2024-12-01,2024,12,1,2,14.932647,1.46219,6.136750,...,1016.6,1036.2,None,4.5,85.0,9.0,0.0,0.0,0.0,0.0
4466,62Z0211989286227,Б,2024-12-01,2024,12,1,3,14.363785,1.46219,6.136750,...,1016.4,1035.9,None,6.0,100.0,11.9,0.0,0.0,0.0,0.0
4467,62Z0211989286227,Б,2024-12-01,2024,12,1,4,13.794922,1.46219,6.136750,...,1016.0,1035.5,None,6.4,101.0,12.6,0.0,0.0,0.0,0.0
4468,62Z0211989286227,Б,2024-12-01,2024,12,1,5,13.937137,1.46219,6.136750,...,1015.7,1035.2,None,6.4,117.0,11.9,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4612447,62Z9997819406173,Б,2024-01-31,2024,1,31,20,25.794128,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612448,62Z9997819406173,Б,2024-01-31,2024,1,31,21,25.204357,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612449,62Z9997819406173,Б,2024-01-31,2024,1,31,22,23.646472,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612450,62Z9997819406173,Б,2024-01-31,2024,1,31,23,21.532199,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4612451,62Z9997819406173,Б,2024-01-31,2024,1,31,24,19.484693,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# df = pd.read_parquet('data/raw/full_concated_copy.parquet')
# df.to_parquet('data/raw/full_concated_copy.parquet')
# df

,EIC-код,Група,Дата,Year,Month,Day,Hour,Sum of кВт,Average of Ціна розподілу ЕЕ грн. без ПДВ/кВт*год,Average of Ціна ЕЕ грн. без ПДВ/кВт*год,...,surface_pressure,pressure_msl,visibility,wind_speed_10m,wind_direction_10m,wind_gusts_10m,shortwave_radiation,direct_radiation,diffuse_radiation,direct_normal_irradiance
0,62Z0008583037334,Б,2024-12-01,2024,12,1,1,20.716983,2.15221,6.136750,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,62Z0008583037334,Б,2024-12-01,2024,12,1,2,19.365875,2.15221,6.136750,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,62Z0008583037334,Б,2024-12-01,2024,12,1,3,18.529475,2.15221,6.136750,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,62Z0008583037334,Б,2024-12-01,2024,12,1,4,18.207783,2.15221,6.136750,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,62Z0008583037334,Б,2024-12-01,2024,12,1,5,17.886091,2.15221,6.136750,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5454708,62Z9997819406173,Б,2024-01-31,2024,1,31,20,25.794128,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5454709,62Z9997819406173,Б,2024-01-31,2024,1,31,21,25.204357,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5454710,62Z9997819406173,Б,2024-01-31,2024,1,31,22,23.646472,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5454711,62Z9997819406173,Б,2024-01-31,2024,1,31,23,21.532199,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5454712,62Z9997819406173,Б,2024-01-31,2024,1,31,24,19.484693,1.63103,3.662765,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN